import {
  FrameIcon,
  PanelTop,
  PanelLeft,
  PanelBottom,
  Search,
  TerminalSquare,
  Move,
  Map,
  Compass,
  Settings,
  BookOpen,
  Library,
  Paintbrush,
  LayoutTemplate,
  type LucideIcon,
} from 'lucide-react';
import type { AgentDocEntry, ComponentEntry, HudsonSettings } from './types';

export const DEFAULT_SETTINGS: HudsonSettings = {
  glowIntensity: 30,
  connectorStyle: 'dashed',
  zoomSensitivity: 1.0,
  masterMute: false,
  uiClickSounds: true,
  uiTransitionSounds: true,
  aiMode: 'cli',
};

export const NAV_ITEMS: { id: string; label: string; icon: LucideIcon }[] = [
  { id: 'overview', label: 'Overview', icon: Compass },
  { id: 'reference', label: 'Reference', icon: Library },
  { id: 'guides', label: 'Guides', icon: BookOpen },
  { id: 'theming', label: 'Theming', icon: Paintbrush },
  { id: 'layout', label: 'Layout', icon: LayoutTemplate },
  { id: 'settings', label: 'Settings', icon: Settings },
];

export const COMPONENTS: ComponentEntry[] = [
  {
    id: 'frame', ns: 'hudson.chrome.frame', label: 'Frame', icon: FrameIcon,
    desc: 'Layout container with 3-layer architecture',
    overview: 'The root shell that orchestrates three rendering layers: Canvas (background pan/zoom grid), World Content (scaled children), and HUD Chrome (fixed viewport overlays). Supports both canvas mode with full pan/zoom and a static panel mode for layout-only apps.',
    props: [
      { name: 'mode', type: "'canvas' | 'panel'", desc: 'Canvas enables pan/zoom; panel renders scrollable content' },
      { name: 'panOffset', type: '{ x, y }', desc: 'Current pan position in world coordinates' },
      { name: 'scale', type: 'number', desc: 'Zoom level (0.2\u20133.0)' },
      { name: 'hud', type: 'ReactNode', desc: 'Chrome UI rendered in the fixed viewport layer' },
      { name: 'canvasProps', type: 'CanvasConfig', desc: 'Forward crosshair guide settings to Canvas' },
      { name: 'children', type: 'ReactNode', desc: 'World-space content that scales with pan/zoom' },
    ],
    usage: '<Frame mode="canvas" panOffset={pan} scale={zoom} hud={<>...</>}>\n  {worldContent}\n</Frame>',
    notes: ['Pan/zoom props are optional \u2014 defaults to origin at 1x', 'Wheel zoom targets cursor position'],
    position: { x: -380, y: -320 },
  },
  {
    id: 'navigation-bar', ns: 'hudson.chrome.navigation-bar', label: 'NavigationBar', icon: PanelTop,
    desc: 'Top bar with branding, search, actions',
    overview: 'Fixed top chrome bar with left-aligned branding (title + subtitle), optional center slot, and right-aligned actions area with an integrated search field. The search field supports filtering with a clear button.',
    props: [
      { name: 'title', type: 'string', desc: 'App name displayed in bold tracking' },
      { name: 'subtitle', type: 'ReactNode', desc: 'Version or context label' },
      { name: 'search', type: '{ value, onChange, placeholder }', desc: 'Integrated filter/search field' },
      { name: 'actions', type: 'ReactNode', desc: 'Buttons rendered before the search field' },
      { name: 'center', type: 'ReactNode', desc: 'Optional center content slot' },
    ],
    usage: '<NavigationBar\n  title="MYAPP"\n  subtitle="v1.0"\n  search={{ value, onChange }}\n  actions={<MuteButton />}\n/>',
    position: { x: 380, y: -320 },
  },
  {
    id: 'side-panel', ns: 'hudson.chrome.side-panel', label: 'SidePanel', icon: PanelLeft,
    desc: 'Collapsible left/right panels with resize',
    overview: 'Docked side panel with a header (icon + title + collapse button), scrollable content area, and a pinned footer slot. Supports drag-to-resize via an edge handle. Returns null when collapsed.',
    props: [
      { name: 'side', type: "'left' | 'right'", desc: 'Which edge to dock to' },
      { name: 'title', type: 'string', desc: 'Header label' },
      { name: 'icon', type: 'ReactNode', desc: 'Icon rendered before the title' },
      { name: 'footer', type: 'ReactNode', desc: 'Pinned content below the scroll area (e.g. Minimap)' },
      { name: 'width', type: 'number', desc: 'Panel width in px (200\u2013500)' },
      { name: 'onResizeStart', type: '(e) => void', desc: 'Drag handle mousedown handler' },
    ],
    usage: '<SidePanel side="left" title="Nav" icon={<Compass />}\n  footer={<Minimap />}>\n  {navItems}\n</SidePanel>',
    notes: ['Footer stays visible during scroll', 'Resize handle appears on the inner edge'],
    position: { x: -380, y: 80 },
  },
  {
    id: 'status-bar', ns: 'hudson.chrome.status-bar', label: 'StatusBar', icon: PanelBottom,
    desc: 'Bottom bar with status, viewport, clock',
    overview: 'Fixed bottom chrome with a status indicator (colored dot + label), center viewport data (click to copy coordinates), terminal toggle, system info readout, and a live clock. Supports left/right custom content slots.',
    props: [
      { name: 'status', type: '{ label, color }', desc: 'Status indicator with emerald/amber/red/neutral' },
      { name: 'viewport', type: '{ pan, zoom, canvasSize }', desc: 'Viewport data for center display' },
      { name: 'onToggleTerminal', type: '() => void', desc: 'Terminal drawer toggle callback' },
      { name: 'left / right', type: 'ReactNode', desc: 'Custom content slots on each side' },
    ],
    usage: '<StatusBar\n  status={{ label: "READY", color: "emerald" }}\n  viewport={{ pan, zoom, canvasSize }}\n  onToggleTerminal={toggle}\n/>',
    position: { x: 380, y: 80 },
  },
  {
    id: 'command-palette', ns: 'hudson.overlay.command-palette', label: 'CommandPalette', icon: Search,
    desc: 'Searchable command menu (Cmd+K)',
    overview: 'Modal overlay with fuzzy text search, keyboard navigation (arrow keys + enter), and shortcut badge display. Renders as a centered dialog with backdrop blur. Commands are filtered in real-time as you type.',
    props: [
      { name: 'isOpen', type: 'boolean', desc: 'Controls visibility' },
      { name: 'onClose', type: '() => void', desc: 'Called on Escape or backdrop click' },
      { name: 'commands', type: 'CommandOption[]', desc: 'Array of { id, label, shortcut?, action }' },
    ],
    usage: '<CommandPalette\n  isOpen={open}\n  onClose={() => setOpen(false)}\n  commands={[\n    { id: "save", label: "Save", shortcut: "Cmd+S", action: save }\n  ]}\n/>',
    notes: ['Cmd+K is the conventional trigger', 'Search is case-insensitive substring match'],
    position: { x: -380, y: 480 },
  },
  {
    id: 'terminal-drawer', ns: 'hudson.overlay.terminal-drawer', label: 'TerminalDrawer', icon: TerminalSquare,
    desc: 'Slide-in console drawer',
    overview: 'Bottom-anchored drawer that slides up from the status bar. Supports maximize toggle to fill the viewport. Content slot accepts any React children \u2014 typically used for logs, REPL output, or a shortcuts reference.',
    props: [
      { name: 'isOpen', type: 'boolean', desc: 'Controls slide-in visibility' },
      { name: 'onClose', type: '() => void', desc: 'Called when close button is clicked' },
      { name: 'isMaximized', type: 'boolean', desc: 'Whether drawer fills the viewport' },
      { name: 'onToggleMaximize', type: '() => void', desc: 'Maximize/restore toggle' },
      { name: 'children', type: 'ReactNode', desc: 'Drawer content' },
    ],
    usage: '<TerminalDrawer isOpen={open} onClose={close}\n  isMaximized={max} onToggleMaximize={toggle}>\n  <LogOutput />\n</TerminalDrawer>',
    position: { x: 380, y: 480 },
  },
  {
    id: 'canvas', ns: 'hudson.canvas.engine', label: 'Canvas', icon: Move,
    desc: 'Pan/zoom engine with grid + crosshairs',
    overview: 'The background layer that handles all pan/zoom interaction. Renders a two-layer dot grid (minor + major) that moves with the pan offset. Space+drag to pan, Cmd+scroll to zoom. Optional crosshair guides follow the cursor and toggle with Cmd+\\.',
    props: [
      { name: 'panOffset', type: '{ x, y }', desc: 'Current pan position' },
      { name: 'scale', type: 'number', desc: 'Current zoom level' },
      { name: 'onPan', type: '(delta) => void', desc: 'Pan delta callback' },
      { name: 'showGuides', type: 'boolean', desc: 'Crosshair guide visibility (default false)' },
      { name: 'onGuidesChange', type: '(v) => void', desc: 'Called when Cmd+\\ toggles guides' },
    ],
    usage: '<Canvas panOffset={pan} scale={zoom}\n  onPan={handlePan}\n  showGuides={false}\n/>',
    notes: ['Space key activates grab cursor', 'Stale-space auto-releases after 2.5s'],
    position: { x: -380, y: 880 },
  },
  {
    id: 'minimap', ns: 'hudson.canvas.minimap', label: 'Minimap', icon: Map,
    desc: 'Viewport overview with click-to-navigate',
    overview: 'Embeddable viewport minimap with a dot grid background, center crosshairs, and a viewport rectangle that tracks the current pan/zoom position. Click anywhere on the map to navigate there. Designed to live in a SidePanel footer with its own collapse/expand header.',
    props: [
      { name: 'pan', type: '{ x, y }', desc: 'Current pan offset for viewport rect' },
      { name: 'zoom', type: 'number', desc: 'Current zoom for viewport rect sizing' },
      { name: 'viewportSize', type: '{ width, height }', desc: 'Browser viewport dimensions' },
      { name: 'isCollapsed', type: 'boolean', desc: 'Shows only the header bar when true' },
      { name: 'onNavigate', type: '(pos) => void', desc: 'Called with world coords on click' },
    ],
    usage: '<SidePanel footer={\n  <Minimap pan={pan} zoom={zoom}\n    viewportSize={vp}\n    onNavigate={setPan}\n    onToggleCollapse={toggle} />\n}>',
    notes: ['Width adapts to parent via ResizeObserver', 'Collapsed state shows a clickable header bar'],
    position: { x: 380, y: 880 },
  },
];

export const AGENT_DOCS: AgentDocEntry[] = [
  { slug: 'overview-agent', title: 'Agent Overview', description: 'Dense, structured overview for AI agents', file: 'agent/overview.agent.md', position: { x: 0, y: 1280 } },
  { slug: 'create-app', title: 'Create App', description: 'Task template for creating a new app', file: 'prompts/create-app.md', position: { x: -380, y: 1580 } },
  { slug: 'add-intents', title: 'Add Intents', description: 'Task template for adding intents', file: 'prompts/add-intents.md', position: { x: 380, y: 1580 } },
];
