/**
 * Built-in template definitions.
 * Each entry has a renderBody (JS function body), name, and description.
 * Used to seed the template store on first load.
 *
 * AUTO-GENERATED by scripts/reverse-seed.ts — do not edit manually.
 * Edit the .data/logo-templates/*.js files and re-run:
 *   bun scripts/reverse-seed.ts
 */

export interface BuiltinDef {
  name: string;
  description: string;
  renderBody: string;
  params?: Record<string, unknown>;
}

const negativeSpace: BuiltinDef = {
  name: 'Negative Space',
  description: 'White panes on dark bg. L-shape formed by the gap.',
  renderBody: `\
const { bgColor, paneColor, dimPaneColor, borderRadius, paneRadius, gapWidth, splitX, splitY, padding } = p;
const content = vb - padding * 2;
const vGap = padding + content * splitX;
const hGap = padding + content * splitY;
const leftW = vGap - padding;
const rightX = vGap + gapWidth;
const rightW = vb - padding - rightX;
const topH = hGap - padding;
const bottomY = hGap + gapWidth;
const bottomH = vb - padding - bottomY;
const uid = 'ns' + Math.random().toString(36).slice(2, 6);

let svg = \`<defs>
<linearGradient id="dp-\${uid}" x1="0" y1="0" x2="0" y2="1">
<stop offset="0" stop-color="black" stop-opacity="0"/>
<stop offset="1" stop-color="black" stop-opacity="0.04"/>
</linearGradient>
</defs>\`;

svg += \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>\`;

// Soft ambient glow behind the L-channel
const g1 = 8;
svg += \`<rect x="\${vGap - g1}" y="\${padding - g1}" width="\${gapWidth + g1 * 2}" height="\${content + g1 * 2}" rx="\${gapWidth / 2 + g1}" fill="\${paneColor}" opacity="0.02"/>\`;
svg += \`<rect x="\${padding - g1}" y="\${hGap - g1}" width="\${content + g1 * 2}" height="\${gapWidth + g1 * 2}" rx="\${gapWidth / 2 + g1}" fill="\${paneColor}" opacity="0.02"/>\`;
const g2 = 3;
svg += \`<rect x="\${vGap - g2}" y="\${padding - g2}" width="\${gapWidth + g2 * 2}" height="\${content + g2 * 2}" rx="\${gapWidth / 2 + g2}" fill="\${paneColor}" opacity="0.035"/>\`;
svg += \`<rect x="\${padding - g2}" y="\${hGap - g2}" width="\${content + g2 * 2}" height="\${gapWidth + g2 * 2}" rx="\${gapWidth / 2 + g2}" fill="\${paneColor}" opacity="0.035"/>\`;

// Main panes — L-shape: left column + bottom row
svg += \`<rect x="\${padding}" y="\${padding}" width="\${leftW}" height="\${content}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;
svg += \`<rect x="\${rightX}" y="\${padding}" width="\${rightW}" height="\${topH}" rx="\${paneRadius}" fill="\${dimPaneColor}"/>\`;
svg += \`<rect x="\${padding}" y="\${bottomY}" width="\${content}" height="\${bottomH}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;

// Subtle depth gradient on L-panes
svg += \`<rect x="\${padding}" y="\${padding}" width="\${leftW}" height="\${content}" rx="\${paneRadius}" fill="url(#dp-\${uid})"/>\`;
svg += \`<rect x="\${padding}" y="\${bottomY}" width="\${content}" height="\${bottomH}" rx="\${paneRadius}" fill="url(#dp-\${uid})"/>\`;

return svg;`,
};

const greenChannel: BuiltinDef = {
  name: 'Green Channel',
  description: 'Dark panes with glowing translucent channel forming the L.',
  renderBody: `\
const { bgColor, paneColor, channelColor, borderRadius, paneRadius, gapWidth, splitX, splitY, padding } = p;
const content = vb - padding * 2;
const vGap = padding + content * splitX;
const hGap = padding + content * splitY;
const rightX = vGap + gapWidth;
const rightW = vb - padding - rightX;
const topH = hGap - padding;
const bottomY = hGap + gapWidth;
const bottomH = vb - padding - bottomY;
const leftW = vGap - padding;

let svg = \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>\`;

// Outer channel glow (wide, faint)
const g1 = 10;
svg += \`<rect x="\${vGap - g1}" y="\${padding}" width="\${gapWidth + g1 * 2}" height="\${topH}" rx="\${gapWidth / 2 + g1}" fill="\${channelColor}" opacity="0.08"/>\`;
svg += \`<rect x="\${vGap - g1}" y="\${hGap}" width="\${gapWidth + g1 * 2}" height="\${gapWidth}" rx="\${gapWidth / 2 + g1}" fill="\${channelColor}" opacity="0.08"/>\`;
svg += \`<rect x="\${rightX}" y="\${hGap - g1}" width="\${rightW}" height="\${gapWidth + g1 * 2}" rx="\${gapWidth / 2 + g1}" fill="\${channelColor}" opacity="0.08"/>\`;

// Inner channel glow (tighter, brighter)
const g2 = 4;
svg += \`<rect x="\${vGap - g2}" y="\${padding}" width="\${gapWidth + g2 * 2}" height="\${topH}" rx="\${gapWidth / 2 + g2}" fill="\${channelColor}" opacity="0.15"/>\`;
svg += \`<rect x="\${vGap - g2}" y="\${hGap - g2}" width="\${gapWidth + g2 * 2}" height="\${gapWidth + g2 * 2}" rx="\${gapWidth / 2 + g2}" fill="\${channelColor}" opacity="0.15"/>\`;
svg += \`<rect x="\${rightX}" y="\${hGap - g2}" width="\${rightW}" height="\${gapWidth + g2 * 2}" rx="\${gapWidth / 2 + g2}" fill="\${channelColor}" opacity="0.15"/>\`;

// Intersection hotspot — brighter where L-arms meet
svg += \`<rect x="\${vGap - 2}" y="\${hGap - 2}" width="\${gapWidth + 4}" height="\${gapWidth + 4}" rx="\${gapWidth / 2 + 2}" fill="\${channelColor}" opacity="0.12"/>\`;

// Dark panes
svg += \`<rect x="\${padding}" y="\${padding}" width="\${leftW}" height="\${content}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;
svg += \`<rect x="\${rightX}" y="\${padding}" width="\${rightW}" height="\${topH}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;
svg += \`<rect x="\${padding}" y="\${bottomY}" width="\${content}" height="\${bottomH}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;

// Channel lines (the actual visible L)
svg += \`<rect x="\${vGap}" y="\${padding}" width="\${gapWidth}" height="\${topH}" rx="2" fill="\${channelColor}"/>\`;
svg += \`<rect x="\${vGap}" y="\${hGap}" width="\${gapWidth}" height="\${gapWidth}" rx="2" fill="\${channelColor}"/>\`;
svg += \`<rect x="\${rightX}" y="\${hGap}" width="\${rightW}" height="\${gapWidth}" rx="2" fill="\${channelColor}"/>\`;

return svg;`,
};

const gridColor: BuiltinDef = {
  name: 'Grid Color',
  description: '2x2 grid. Three L-quadrants filled, one ghosted.',
  renderBody: `\
const { bgColor, paneColor, dimPaneColor, borderRadius, paneRadius, gapWidth, padding } = p;
const uid = 'gc' + Math.random().toString(36).slice(2, 6);
const content = vb - padding * 2;
const cell = (content - gapWidth) / 2;
const x1 = padding;
const y1 = padding;
const x2 = padding + cell + gapWidth;
const y2 = padding + cell + gapWidth;

let svg = \`<defs>
<linearGradient id="gp-\${uid}" x1="0" y1="0" x2="0" y2="1">
<stop offset="0" stop-color="black" stop-opacity="0"/>
<stop offset="1" stop-color="black" stop-opacity="0.035"/>
</linearGradient>
</defs>\`;

svg += \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>\`;

// L-quadrants — top-left, bottom-left, bottom-right (solid fills)
svg += \`<rect x="\${x1}" y="\${y1}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;
svg += \`<rect x="\${x1}" y="\${y2}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;
svg += \`<rect x="\${x2}" y="\${y2}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;

// Depth gradient on L-quadrants
svg += \`<rect x="\${x1}" y="\${y1}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="url(#gp-\${uid})"/>\`;
svg += \`<rect x="\${x1}" y="\${y2}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="url(#gp-\${uid})"/>\`;
svg += \`<rect x="\${x2}" y="\${y2}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="url(#gp-\${uid})"/>\`;

// Ghost quadrant — top-right (outline only)
svg += \`<rect x="\${x2 + 0.5}" y="\${y1 + 0.5}" width="\${cell - 1}" height="\${cell - 1}" rx="\${Math.max(0, paneRadius - 0.5)}" fill="none" stroke="\${dimPaneColor}" stroke-width="1"/>\`;

// Subtle intersection accent
const cx = padding + cell + gapWidth / 2;
const cy = padding + cell + gapWidth / 2;
svg += \`<circle cx="\${cx}" cy="\${cy}" r="\${Math.min(gapWidth * 0.25, 4)}" fill="\${paneColor}" opacity="0.12"/>\`;

return svg;`,
};

const interlocking: BuiltinDef = {
  name: 'Interlocking',
  description: 'Two interlocking L-shaped pieces with subtle depth.',
  renderBody: `\
const { bgColor, paneColor, borderRadius, gapWidth, padding } = p;
const notchR = Number(p.notchRatio) || 0.5;
const secOp = Number(p.secondaryOpacity) || 0.50;
const content = vb - padding * 2;
const cell = (content - gapWidth) / 2;
const notch = cell * notchR;
const arm = cell - notch;
const x1 = padding, x2 = padding + cell + gapWidth;
const y1 = padding, y2 = padding + cell + gapWidth;
const nx = x1 + arm, ny = y1 + arm;
const nx2 = x2 + notch, ny2 = y2 + notch;

let svg = \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>\`;

const p1 = \`M\${x1},\${y1} H\${x1 + cell} V\${ny} H\${nx} V\${y1 + cell} H\${x1} Z\`;
const p2 = \`M\${x2},\${y1} H\${x2 + cell} V\${y1 + cell} H\${nx2} V\${ny} H\${x2} Z\`;
const p3 = \`M\${x1},\${y2} H\${nx} V\${ny2} H\${x1 + cell} V\${y2 + cell} H\${x1} Z\`;
const p4 = \`M\${nx2},\${y2} H\${x2 + cell} V\${y2 + cell} H\${x2} V\${ny2} H\${nx2} Z\`;

svg += \`<path d="\${p1}" fill="black" opacity="0.06" transform="translate(1.5, 1.5)"/>\`;
svg += \`<path d="\${p3}" fill="black" opacity="0.06" transform="translate(1.5, 1.5)"/>\`;

svg += \`<path d="\${p1}" fill="\${paneColor}"/>\`;
svg += \`<path d="\${p3}" fill="\${paneColor}"/>\`;

svg += \`<path d="\${p2}" fill="\${paneColor}" opacity="\${secOp}"/>\`;
svg += \`<path d="\${p4}" fill="\${paneColor}" opacity="\${secOp}"/>\`;

svg += \`<path d="\${p1}" fill="none" stroke="white" stroke-width="0.6" opacity="0.08"/>\`;
svg += \`<path d="\${p3}" fill="none" stroke="white" stroke-width="0.6" opacity="0.08"/>\`;

return svg;`,
  params: {
      "notchRatio": {
          "type": "number",
          "label": "Notch depth",
          "default": 0.5,
          "min": 0.2,
          "max": 0.8,
          "step": 0.05
      },
      "secondaryOpacity": {
          "type": "number",
          "label": "Secondary opacity",
          "default": 0.5,
          "min": 0.1,
          "max": 1,
          "step": 0.05
      }
  },
};

const latticeGrid: BuiltinDef = {
  name: 'Lattice Grid',
  description: 'NxN grid. L highlighted by color with subtle depth.',
  renderBody: `\
const { bgColor, paneColor, dimPaneColor, borderRadius, paneRadius, gapWidth, padding } = p;
const cols = Number(p.gridSize) || 3;
const glowPx = Number(p.glowSize) || 3;
const glowOp = Number(p.glowOpacity) || 0.04;
const content = vb - padding * 2;
const cellSize = (content - gapWidth * (cols - 1)) / cols;
const isL = (col, row) => col === 0 || row === cols - 1;

let svg = \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>\`;

// Faint glow behind L-cells
if (glowPx > 0) {
  for (let row = 0; row < cols; row++) {
    for (let col = 0; col < cols; col++) {
      if (!isL(col, row)) continue;
      const x = padding + col * (cellSize + gapWidth) - glowPx;
      const y = padding + row * (cellSize + gapWidth) - glowPx;
      svg += \`<rect x="\${x}" y="\${y}" width="\${cellSize + glowPx * 2}" height="\${cellSize + glowPx * 2}" rx="\${paneRadius + glowPx}" fill="\${paneColor}" opacity="\${glowOp}"/>\`;
    }
  }
}

// Grid cells
for (let row = 0; row < cols; row++) {
  for (let col = 0; col < cols; col++) {
    const x = padding + col * (cellSize + gapWidth);
    const y = padding + row * (cellSize + gapWidth);
    const inL = isL(col, row);
    svg += \`<rect x="\${x}" y="\${y}" width="\${cellSize}" height="\${cellSize}" rx="\${paneRadius}" fill="\${inL ? paneColor : dimPaneColor}"/>\`;
  }
}

// Tiny accent dots at grid intersections
const dotR = Math.min(gapWidth * 0.18, 2);
if (dotR > 0.5) {
  for (let row = 0; row < cols - 1; row++) {
    for (let col = 0; col < cols - 1; col++) {
      const cx = padding + (col + 1) * cellSize + col * gapWidth + gapWidth / 2;
      const cy = padding + (row + 1) * cellSize + row * gapWidth + gapWidth / 2;
      svg += \`<circle cx="\${cx}" cy="\${cy}" r="\${dotR}" fill="\${paneColor}" opacity="0.10"/>\`;
    }
  }
}

return svg;`,
  params: {
      "gridSize": {
          "type": "number",
          "label": "Grid size",
          "default": 3,
          "min": 2,
          "max": 6,
          "step": 1
      },
      "glowSize": {
          "type": "number",
          "label": "Glow spread",
          "default": 3,
          "min": 0,
          "max": 10,
          "step": 1
      },
      "glowOpacity": {
          "type": "number",
          "label": "Glow intensity",
          "default": 0.04,
          "min": 0,
          "max": 0.15,
          "step": 0.01
      }
  },
};

const appWindows: BuiltinDef = {
  name: 'App Windows',
  description: 'Four panes styled as macOS app windows forming L.',
  renderBody: `\
const { bgColor, borderRadius, paneRadius, gapWidth, padding } = p;
const content = vb - padding * 2;
const cell = (content - gapWidth) / 2;
const x1 = padding, y1 = padding;
const x2 = padding + cell + gapWidth, y2 = padding + cell + gapWidth;
const tb = 14, dr = 1.8, dg = 5.5, d0 = 8;
const lBg = '#2c2c2e', lTitle = 'rgba(255,255,255,0.10)';
const xBg = '#242440', xTitle = 'rgba(88,86,214,0.20)';
const uid = Math.random().toString(36).slice(2, 6);

function dots(cx, cy) {
  return \`<circle cx="\${cx+d0}" cy="\${cy}" r="\${dr}" fill="#ff5f57" opacity="0.8"/>
<circle cx="\${cx+d0+dg}" cy="\${cy}" r="\${dr}" fill="#ffbd2e" opacity="0.8"/>
<circle cx="\${cx+d0+dg*2}" cy="\${cy}" r="\${dr}" fill="#28ca42" opacity="0.8"/>\`;
}

function win(wx, wy, bg, titleFill, clipId, contentSvg) {
  // Subtle shadow behind window
  let s = \`<rect x="\${wx + 2}" y="\${wy + 2}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="black" opacity="0.12"/>\`;
  s += \`<g>
<rect x="\${wx}" y="\${wy}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="\${bg}"/>
<defs><clipPath id="\${clipId}"><rect x="\${wx}" y="\${wy}" width="\${cell}" height="\${cell}" rx="\${paneRadius}"/></clipPath></defs>
<g clip-path="url(#\${clipId})">
  <rect x="\${wx}" y="\${wy}" width="\${cell}" height="\${tb}" fill="\${titleFill}"/>
  <line x1="\${wx}" y1="\${wy+tb}" x2="\${wx+cell}" y2="\${wy+tb}" stroke="rgba(255,255,255,0.04)" stroke-width="0.5"/>
</g>
\${dots(wx, wy+tb/2)}
\${contentSvg}
</g>\`;
  return s;
}

const iterm = Array.from({length:5}, (_,i) => {
  const widths = [0.55,0.35,0.65,0.45,0.5];
  const ops = [0.65,0.45,0.35,0.5,0.4];
  return \`<rect x="\${x1+8}" y="\${y1+tb+10+i*9}" width="\${cell*widths[i]}" height="3" rx="1" fill="rgba(51,199,115,\${ops[i]})"/>\`;
}).join('');

const preview = \`<rect x="\${x1+cell*0.15}" y="\${y2+tb+cell*0.1}" width="\${cell*0.7}" height="\${cell*0.55}" rx="4" fill="rgba(255,255,255,0.08)"/>
<rect x="\${x1+cell*0.3}" y="\${y2+tb+cell*0.25}" width="\${cell*0.4}" height="\${cell*0.2}" rx="3" fill="rgba(255,255,255,0.12)"/>\`;

const chrome = \`<rect x="\${x2+8}" y="\${y2+tb+8}" width="\${cell-16}" height="9" rx="4.5" fill="rgba(255,255,255,0.10)"/>
\${[0.7,0.5,0.6,0.45].map((w,i) => \`<rect x="\${x2+8}" y="\${y2+tb+26+i*9}" width="\${cell*w}" height="3" rx="1" fill="rgba(255,255,255,\${0.15-i*0.02})"/>\`).join('')}\`;

const xcode = [0.4,0.55,0.35,0.4,0.5,0.3].map((w,i) => {
  const indent = [8,16,16,24,16,8][i];
  const ops = [0.55,0.35,0.40,0.30,0.35,0.50][i];
  return \`<rect x="\${x2+indent}" y="\${y1+tb+10+i*9}" width="\${cell*w}" height="3" rx="1" fill="rgba(120,118,240,\${ops})"/>\`;
}).join('');

return \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>
\${win(x1,y1,lBg,lTitle,'aw-tl-'+uid,iterm)}
\${win(x1,y2,lBg,lTitle,'aw-bl-'+uid,preview)}
\${win(x2,y2,lBg,lTitle,'aw-br-'+uid,chrome)}
\${win(x2,y1,xBg,xTitle,'aw-tr-'+uid,xcode)}\`;`,
};

const dotMatrix: BuiltinDef = {
  name: 'Dot Matrix',
  description: 'Stippled dot field. L-shape emerges from density and brightness.',
  renderBody: `\
const { bgColor, paneColor, dimPaneColor, borderRadius, splitX, splitY, padding } = p;
const step = Number(p.dotSpacing) || 12;
const base = Number(p.dotSize) || 2.4;
const decay = Number(p.falloffRate) || 0.35;
const content = vb - padding * 2;
const cols = Math.floor(content / step) + 1;
const rows = Math.floor(content / step) + 1;
const ox = padding + (content - (cols - 1) * step) / 2;
const oy = padding + (content - (rows - 1) * step) / 2;
const sC = Math.round(cols * splitX);
const sR = Math.round(rows * splitY);

function hash(a, b) {
  let n = ((a * 2654435761) ^ (b * 2246822519)) >>> 0;
  n = ((n >> 16) ^ n) >>> 0;
  return (n % 1000) / 1000;
}

let svg = \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>\`;

for (let r = 0; r < rows; r++) {
  for (let c = 0; c < cols; c++) {
    const cx = (ox + c * step).toFixed(1);
    const cy = (oy + r * step).toFixed(1);
    const inL = c < sC || r >= sR;

    const dCol = c < sC ? 0 : c - sC;
    const dRow = r >= sR ? 0 : sR - r;
    const dToL = inL ? 0 : Math.min(dCol, dRow);

    const falloff = Math.exp(-dToL * decay);
    const h = hash(c, r);
    const jitter = 0.85 + h * 0.3;

    let dr, op, fill;
    if (inL) {
      dr = base * (0.9 + h * 0.25) * jitter;
      op = 0.65 + h * 0.25;
      fill = paneColor;
    } else {
      dr = base * 0.45 * falloff * jitter + base * 0.2;
      op = 0.15 + 0.55 * falloff;
      fill = falloff > 0.5 ? paneColor : dimPaneColor;
    }

    svg += \`<circle cx="\${cx}" cy="\${cy}" r="\${dr.toFixed(2)}" fill="\${fill}" opacity="\${op.toFixed(2)}"/>\`;
  }
}
return svg;`,
  params: {
      "dotSpacing": {
          "type": "number",
          "label": "Dot spacing",
          "default": 12,
          "min": 6,
          "max": 24,
          "step": 1
      },
      "dotSize": {
          "type": "number",
          "label": "Dot size",
          "default": 2.4,
          "min": 1,
          "max": 5,
          "step": 0.1
      },
      "falloffRate": {
          "type": "number",
          "label": "Edge falloff",
          "default": 0.35,
          "min": 0.1,
          "max": 1,
          "step": 0.05
      }
  },
};

const mosaic: BuiltinDef = {
  name: 'Mosaic',
  description: 'Dissolving tile grid. L emerges through size and opacity falloff.',
  renderBody: `\
const { bgColor, paneColor, dimPaneColor, borderRadius, paneRadius, gapWidth, padding } = p;
const cols = Number(p.gridSize) || 5;
const curve = Number(p.falloffCurve) || 1.8;
const minSc = Number(p.minScale) || 0.15;
const content = vb - padding * 2;
const cellSize = (content - gapWidth * (cols - 1)) / cols;
const maxR = Math.min(paneRadius, cellSize / 2);

function dist(col, row) {
  const dCol = col;
  const dRow = (cols - 1) - row;
  return Math.min(dCol, dRow);
}

const maxDist = cols - 1;

let svg = \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>\`;

for (let row = 0; row < cols; row++) {
  for (let col = 0; col < cols; col++) {
    const cx = padding + col * (cellSize + gapWidth) + cellSize / 2;
    const cy = padding + row * (cellSize + gapWidth) + cellSize / 2;
    const d = dist(col, row);

    if (d === 0) {
      const x = cx - cellSize / 2;
      const y = cy - cellSize / 2;
      svg += \`<rect x="\${x - 3}" y="\${y - 3}" width="\${cellSize + 6}" height="\${cellSize + 6}" rx="\${maxR + 3}" fill="\${paneColor}" opacity="0.05"/>\`;
      svg += \`<rect x="\${x}" y="\${y}" width="\${cellSize}" height="\${cellSize}" rx="\${maxR}" fill="\${paneColor}"/>\`;
    } else {
      const t = d / maxDist;
      const scale = Math.max(minSc, Math.pow(1 - t, curve));
      const opacity = Math.max(0.04, Math.pow(1 - t, curve + 0.2));
      const s = cellSize * scale;
      const x = cx - s / 2;
      const y = cy - s / 2;
      const sr = Math.min(maxR * (1 + d * 0.35), s / 2);
      svg += \`<rect x="\${x}" y="\${y}" width="\${s}" height="\${s}" rx="\${sr}" fill="\${dimPaneColor}" opacity="\${opacity.toFixed(2)}"/>\`;
    }
  }
}
return svg;`,
  params: {
      "gridSize": {
          "type": "number",
          "label": "Grid size",
          "default": 5,
          "min": 3,
          "max": 8,
          "step": 1
      },
      "falloffCurve": {
          "type": "number",
          "label": "Falloff curve",
          "default": 1.8,
          "min": 0.5,
          "max": 4,
          "step": 0.1
      },
      "minScale": {
          "type": "number",
          "label": "Min tile scale",
          "default": 0.15,
          "min": 0,
          "max": 0.5,
          "step": 0.05
      }
  },
};

const tDecoration: BuiltinDef = {
  name: 'T Decoration',
  description: 'Lowercase t with parametric decoration treatments (Talkie brand). Single template covering the cassette/audio mark catalog: stem-top indicators, T-cross marks, crossbar treatments, surface effects.',
  renderBody: `\
const {
  glyphScale, glyphInk, glyphFontWeight, glyphFontFamily,
  showCanvas, canvasColor, canvasRadius,
  decoration, decorationColor, decorationScale, decorationOpacity,
  dotShape, dotOffsetY, showHalo, haloOpacity,
} = p;

// ── Glyph geometry (calibrated for JBM Medium, baseline = size * 0.86) ──
const T_CELL_CENTER = 0.31;
const T_STEM_OFFSET_FROM_ANCHOR = -0.034;
const T_STEM_WIDTH = 0.08;
const T_CROSS_Y = 0.469;
const T_CROSSBAR_LEFT = 0.115;
const T_CROSSBAR_RIGHT = 0.4825;

// ── Map to vb-square canvas (Logo Designer renders at vb=512) ──
const size  = vb * glyphScale;
const cellW = size * 0.62;
const originX = (vb - cellW) / 2;
const originY = (vb - size) / 2;

const anchorX       = originX + size * T_CELL_CENTER;
const baseline      = originY + size * 0.86;
const stemCx        = anchorX + size * T_STEM_OFFSET_FROM_ANCHOR;
const crossY        = originY + size * T_CROSS_Y;
const stemW         = size * T_STEM_WIDTH;
const crossbarLeft  = originX + size * T_CROSSBAR_LEFT;
const crossbarRight = originX + size * T_CROSSBAR_RIGHT;
const stemTopY      = originY + size * 0.14;
const stemBaseline  = originY + size * 0.86;
const dotCy         = originY + size * 0.12;

const uid = 'td' + Math.random().toString(36).slice(2, 6);
const fontSize = size * 0.78;

// ── Mutable render state ──
let defsBlock  = '';
let beforeParts = [];   // emitted between canvas + glyph (behind the t)
let afterParts  = [];   // emitted after glyph (in front)
let glyphFill  = glyphInk;
let glyphStyle = '';
let glyphMaskAttr = '';

// ── Helper: render the configurable decoration "dot" shape ──
function dotShapeSvg(cx, cy, baseR, fill, opacity) {
  const r = baseR * decorationScale;
  if (dotShape === 'square') {
    const w = r * 2;
    return \`<rect x="\${cx - r}" y="\${cy - r}" width="\${w}" height="\${w}" fill="\${fill}" opacity="\${opacity}"/>\`;
  }
  if (dotShape === 'rounded-square') {
    const w = r * 2;
    return \`<rect x="\${cx - r}" y="\${cy - r}" width="\${w}" height="\${w}" rx="\${r * 0.35}" fill="\${fill}" opacity="\${opacity}"/>\`;
  }
  if (dotShape === 'rect-wide') {
    return \`<rect x="\${cx - r * 1.4}" y="\${cy - r * 0.65}" width="\${r * 2.8}" height="\${r * 1.3}" rx="\${r * 0.5}" fill="\${fill}" opacity="\${opacity}"/>\`;
  }
  if (dotShape === 'rect-tall') {
    return \`<rect x="\${cx - r * 0.65}" y="\${cy - r * 1.4}" width="\${r * 1.3}" height="\${r * 2.8}" rx="\${r * 0.5}" fill="\${fill}" opacity="\${opacity}"/>\`;
  }
  return \`<circle cx="\${cx}" cy="\${cy}" r="\${r}" fill="\${fill}" opacity="\${opacity}"/>\`;
}

switch (decoration) {
  case 'none':
    break;

  case 'stem-top-dot': {
    const baseR = stemW * 0.5;
    const cy = dotCy + dotOffsetY;
    if (showHalo) {
      afterParts.push(\`<circle cx="\${stemCx}" cy="\${cy}" r="\${baseR * decorationScale * 3}" fill="\${decorationColor}" opacity="\${haloOpacity * 0.5}"/>\`);
      afterParts.push(\`<circle cx="\${stemCx}" cy="\${cy}" r="\${baseR * decorationScale * 1.8}" fill="\${decorationColor}" opacity="\${haloOpacity}"/>\`);
    }
    afterParts.push(dotShapeSvg(stemCx, cy, baseR, decorationColor, decorationOpacity));
    break;
  }

  case 'stem-top-lamp': {
    const baseR = stemW * 0.5 * decorationScale;
    const cy = dotCy + dotOffsetY;
    afterParts.push(\`<circle cx="\${stemCx}" cy="\${cy}" r="\${baseR * 3}" fill="\${decorationColor}" opacity="\${0.08 * decorationOpacity}"/>\`);
    afterParts.push(\`<circle cx="\${stemCx}" cy="\${cy}" r="\${baseR * 1.8}" fill="\${decorationColor}" opacity="\${0.15 * decorationOpacity}"/>\`);
    afterParts.push(\`<circle cx="\${stemCx}" cy="\${cy}" r="\${baseR}" fill="\${decorationColor}" opacity="\${decorationOpacity}"/>\`);
    afterParts.push(\`<circle cx="\${stemCx}" cy="\${cy}" r="\${baseR * 0.5}" fill="#FCEBD5" opacity="\${0.8 * decorationOpacity}"/>\`);
    break;
  }

  case 'cross-chip': {
    const w = stemW * 0.68 * decorationScale;
    afterParts.push(\`<rect x="\${stemCx - w / 2}" y="\${crossY - w / 2}" width="\${w}" height="\${w}" fill="\${decorationColor}" opacity="\${decorationOpacity}"/>\`);
    break;
  }

  case 'cross-knockout': {
    const w = stemW * 0.7 * decorationScale;
    defsBlock += \`<mask id="m-\${uid}"><rect width="100%" height="100%" fill="white"/><rect x="\${stemCx - w / 2}" y="\${crossY - w / 2}" width="\${w}" height="\${w}" fill="black"/></mask>\`;
    glyphMaskAttr = \` mask="url(#m-\${uid})"\`;
    break;
  }

  case 'cross-flush-cap': {
    const w = stemW * decorationScale;
    afterParts.push(\`<rect x="\${stemCx - w / 2}" y="\${crossY - w / 2}" width="\${w}" height="\${w}" fill="\${decorationColor}" opacity="\${decorationOpacity}"/>\`);
    break;
  }

  case 'cross-registration': {
    const w = stemW * 1.15 * decorationScale;
    const sw = Math.max(0.75, size * 0.005);
    afterParts.push(\`<rect x="\${stemCx - w / 2}" y="\${crossY - w / 2}" width="\${w}" height="\${w}" fill="none" stroke="\${decorationColor}" stroke-width="\${sw}" opacity="\${decorationOpacity}"/>\`);
    break;
  }

  case 'cross-annotation': {
    const w = stemW * 0.55 * decorationScale;
    const gap = stemW * 0.55;
    const x = stemCx + stemW / 2 + gap;
    const y = (originY + size * 0.43) - w;
    afterParts.push(\`<rect x="\${x}" y="\${y}" width="\${w}" height="\${w}" fill="\${decorationColor}" opacity="\${decorationOpacity}"/>\`);
    break;
  }

  case 'crossbar-caps': {
    const w = stemW * decorationScale;
    const gap = stemW * 0.45;
    const xL = crossbarLeft - gap - w;
    const xR = crossbarRight + gap;
    const y = crossY - w / 2;
    afterParts.push(\`<g fill="\${decorationColor}" opacity="\${decorationOpacity}"><rect x="\${xL}" y="\${y}" width="\${w}" height="\${w}"/><rect x="\${xR}" y="\${y}" width="\${w}" height="\${w}"/></g>\`);
    break;
  }

  case 'crossbar-pin': {
    const r = stemW * 0.25 * decorationScale;
    afterParts.push(\`<circle cx="\${crossbarRight}" cy="\${crossY}" r="\${r}" fill="\${decorationColor}" opacity="\${decorationOpacity}"/>\`);
    break;
  }

  case 'crossbar-slot': {
    const slotW = stemW * 0.35 * decorationScale;
    const slotH = stemW * 1.4 * decorationScale;
    const sx = stemCx + stemW * 1.8;
    defsBlock += \`<mask id="m-\${uid}"><rect width="100%" height="100%" fill="white"/><rect x="\${sx - slotW / 2}" y="\${crossY - slotH / 2}" width="\${slotW}" height="\${slotH}" fill="black"/></mask>\`;
    glyphMaskAttr = \` mask="url(#m-\${uid})"\`;
    break;
  }

  case 'stem-dot': {
    const r = stemW * 0.28 * decorationScale;
    const y = crossY + (stemBaseline - crossY) * 0.45;
    afterParts.push(\`<circle cx="\${stemCx}" cy="\${y}" r="\${r}" fill="\${decorationColor}" opacity="\${decorationOpacity}"/>\`);
    break;
  }

  case 'stem-foot': {
    const tickW = stemW * 1.6 * decorationScale;
    const tickH = Math.max(1.5, size * 0.008);
    const y = stemBaseline + size * 0.01;
    afterParts.push(\`<rect x="\${stemCx - tickW / 2}" y="\${y}" width="\${tickW}" height="\${tickH}" fill="\${decorationColor}" opacity="\${decorationOpacity}"/>\`);
    break;
  }

  case 'stem-cross-hairline': {
    const len = stemW * 1.8 * decorationScale;
    const sw = Math.max(0.75, size * 0.004);
    afterParts.push(\`<line x1="\${stemCx - len}" y1="\${crossY + len * 0.6}" x2="\${stemCx + len}" y2="\${crossY - len * 0.6}" stroke="\${decorationColor}" stroke-width="\${sw}" opacity="\${decorationOpacity}"/>\`);
    break;
  }

  case 'ascender-notch': {
    const w = stemW * 0.5 * decorationScale;
    const y = originY + size * 0.155;
    defsBlock += \`<mask id="m-\${uid}"><rect width="100%" height="100%" fill="white"/><rect x="\${stemCx - w / 2}" y="\${y}" width="\${w}" height="\${w}" fill="black"/></mask>\`;
    glyphMaskAttr = \` mask="url(#m-\${uid})"\`;
    break;
  }

  case 'descender-hook-accent': {
    const w = stemW * 0.4 * decorationScale;
    const x = stemCx - stemW * 0.8;
    const y = stemBaseline - stemW * 0.2;
    afterParts.push(\`<rect data-element-id="descender-hook" x="\${x}" y="\${y}" width="\${w}" height="\${w}" rx="\${w * 0.15}" fill="\${decorationColor}" opacity="\${decorationOpacity}"/>\`);
    break;
  }

  case 'gradient-fill': {
    defsBlock += \`<linearGradient id="g-\${uid}" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="\${decorationColor}"/><stop offset="100%" stop-color="#6B4422"/></linearGradient>\`;
    glyphFill = \`url(#g-\${uid})\`;
    break;
  }

  case 'glow-halo': {
    defsBlock += \`<filter id="f-\${uid}" x="-30%" y="-30%" width="160%" height="160%"><feGaussianBlur stdDeviation="6" result="b1"/><feGaussianBlur in="SourceGraphic" stdDeviation="2" result="b2"/><feMerge><feMergeNode in="b1"/><feMergeNode in="b2"/><feMergeNode in="SourceGraphic"/></feMerge></filter>\`;
    afterParts.push(\`<text x="\${anchorX}" y="\${baseline}" text-anchor="middle" font-family="\${glyphFontFamily}" font-weight="\${glyphFontWeight}" font-size="\${fontSize}" fill="none" stroke="\${decorationColor}" stroke-width="2" filter="url(#f-\${uid})" opacity="\${0.7 * decorationOpacity}">t</text>\`);
    break;
  }

  case 'debossed': {
    glyphFill = '#B8A88E';
    defsBlock += \`<filter id="f-\${uid}" x="-5%" y="-5%" width="110%" height="110%"><feGaussianBlur in="SourceAlpha" stdDeviation="2.5" result="blur"/><feOffset dx="1.5" dy="2.5" result="off"/><feFlood flood-color="#0E0D0A" flood-opacity="0.55" result="c"/><feComposite in="c" in2="off" operator="in" result="shadow"/><feOffset in="SourceAlpha" dx="-1" dy="-1.5" result="off2"/><feGaussianBlur in="off2" stdDeviation="1.5" result="blur2"/><feFlood flood-color="#F4EFE6" flood-opacity="0.3" result="c2"/><feComposite in="c2" in2="blur2" operator="in" result="hi"/><feMerge><feMergeNode in="shadow"/><feMergeNode in="hi"/><feMergeNode in="SourceGraphic"/></feMerge></filter>\`;
    glyphStyle = \` style="filter:url(#f-\${uid})"\`;
    break;
  }

  case 'chrome': {
    defsBlock += \`<linearGradient id="g-\${uid}" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#E8E8E8"/><stop offset="25%" stop-color="#A0A0A0"/><stop offset="50%" stop-color="#D4D4D4"/><stop offset="75%" stop-color="#8A8A8A"/><stop offset="100%" stop-color="#C0C0C0"/></linearGradient>\`;
    glyphFill = \`url(#g-\${uid})\`;
    break;
  }

  case 'tape-spool': {
    const cx1 = originX + cellW * 0.28;
    const cx2 = originX + cellW * 0.72;
    const cy = originY + size * 0.58;
    const rr = size * 0.16 * decorationScale;
    beforeParts.push(\`<g stroke="\${decorationColor}" fill="none" opacity="\${0.18 * decorationOpacity}"><circle cx="\${cx1}" cy="\${cy}" r="\${rr}" stroke-width="1.5"/><circle cx="\${cx1}" cy="\${cy}" r="\${rr * 0.45}" stroke-width="1"/><circle cx="\${cx2}" cy="\${cy}" r="\${rr * 0.8}" stroke-width="1.5"/><circle cx="\${cx2}" cy="\${cy}" r="\${rr * 0.35}" stroke-width="1"/></g>\`);
    break;
  }

  case 'letterpress': {
    defsBlock += \`<filter id="f-\${uid}" x="-5%" y="-5%" width="110%" height="110%"><feTurbulence type="fractalNoise" baseFrequency="0.04" numOctaves="4" result="noise"/><feDisplacementMap in="SourceGraphic" in2="noise" scale="3" xChannelSelector="R" yChannelSelector="G"/></filter>\`;
    glyphStyle = \` style="filter:url(#f-\${uid})"\`;
    break;
  }
}

// ── Compose final SVG ──
let svg = '';
if (showCanvas) {
  svg += \`<rect width="\${vb}" height="\${vb}" rx="\${canvasRadius}" fill="\${canvasColor}"/>\`;
}
if (defsBlock) svg += \`<defs>\${defsBlock}</defs>\`;
svg += beforeParts.join('');
svg += \`<text data-element-id="glyph" x="\${anchorX}" y="\${baseline}" text-anchor="middle" font-family="\${glyphFontFamily}" font-weight="\${glyphFontWeight}" font-size="\${fontSize}" fill="\${glyphFill}"\${glyphMaskAttr}\${glyphStyle}>t</text>\`;
svg += afterParts.join('');

return svg;`,
  params: {
      "glyphScale": {
          "label": "Glyph size",
          "type": "number",
          "default": 0.85,
          "min": 0.4,
          "max": 1,
          "step": 0.01,
          "group": "Glyph"
      },
      "glyphInk": {
          "label": "Glyph color",
          "type": "color",
          "default": "#F4EFE6",
          "group": "Glyph"
      },
      "glyphFontWeight": {
          "label": "Glyph weight",
          "type": "enum",
          "default": "500",
          "options": [
              "300",
              "400",
              "500",
              "600",
              "700"
          ],
          "group": "Glyph"
      },
      "glyphFontFamily": {
          "label": "Glyph family",
          "type": "text",
          "default": "JetBrains Mono",
          "placeholder": "JetBrains Mono",
          "group": "Glyph"
      },
      "showCanvas": {
          "label": "Show canvas",
          "type": "toggle",
          "default": true,
          "group": "Canvas"
      },
      "canvasColor": {
          "label": "Canvas color",
          "type": "color",
          "default": "#0E0D0A",
          "group": "Canvas"
      },
      "canvasRadius": {
          "label": "Canvas radius",
          "type": "number",
          "default": 40,
          "min": 0,
          "max": 256,
          "step": 1,
          "group": "Canvas"
      },
      "decoration": {
          "label": "Decoration",
          "type": "enum",
          "default": "stem-top-dot",
          "options": [
              "none",
              "stem-top-dot",
              "stem-top-lamp",
              "cross-chip",
              "cross-knockout",
              "cross-flush-cap",
              "cross-registration",
              "cross-annotation",
              "crossbar-caps",
              "crossbar-pin",
              "crossbar-slot",
              "stem-dot",
              "stem-foot",
              "stem-cross-hairline",
              "ascender-notch",
              "descender-hook-accent",
              "gradient-fill",
              "glow-halo",
              "debossed",
              "chrome",
              "tape-spool",
              "letterpress"
          ],
          "group": "Decoration"
      },
      "decorationColor": {
          "label": "Decoration color",
          "type": "color",
          "default": "#FF5346",
          "group": "Decoration"
      },
      "decorationScale": {
          "label": "Decoration scale",
          "type": "number",
          "default": 1,
          "min": 0.25,
          "max": 2.5,
          "step": 0.05,
          "group": "Decoration"
      },
      "decorationOpacity": {
          "label": "Decoration opacity",
          "type": "number",
          "default": 1,
          "min": 0,
          "max": 1,
          "step": 0.05,
          "group": "Decoration"
      },
      "dotShape": {
          "label": "Dot shape",
          "type": "enum",
          "default": "circle",
          "options": [
              "circle",
              "square",
              "rounded-square",
              "rect-wide",
              "rect-tall"
          ],
          "group": "Dot"
      },
      "dotOffsetY": {
          "label": "Dot y-offset",
          "type": "number",
          "default": 0,
          "min": -200,
          "max": 200,
          "step": 1,
          "group": "Dot"
      },
      "showHalo": {
          "label": "Show halo",
          "type": "toggle",
          "default": false,
          "group": "Dot"
      },
      "haloOpacity": {
          "label": "Halo opacity",
          "type": "number",
          "default": 0.15,
          "min": 0,
          "max": 1,
          "step": 0.05,
          "group": "Dot"
      }
  },
};

export const builtinRenderBodies: Record<string, BuiltinDef> = {
  'negative-space': negativeSpace,
  'green-channel': greenChannel,
  'grid-color': gridColor,
  'interlocking': interlocking,
  'lattice-grid': latticeGrid,
  'app-windows': appWindows,
  'dot-matrix': dotMatrix,
  'mosaic': mosaic,
  't-decoration': tDecoration,
};
