import type { AppIntent } from 'hudsonkit';

export const logoIntents: AppIntent[] = [
  {
    commandId: 'logo:tool-select',
    title: 'Use Select Tool',
    description: 'Switch Logo Designer to selection mode for moving and editing components.',
    category: 'tool',
    keywords: ['select', 'pointer', 'move component', 'logo component'],
    shortcut: 'V',
  },
  {
    commandId: 'logo:tool-rectangle',
    title: 'Use Rectangle Tool',
    description: 'Switch Logo Designer to rectangle drawing mode.',
    category: 'tool',
    keywords: ['rectangle', 'rect', 'box', 'draw shape', 'logo component'],
    shortcut: 'R',
  },
  {
    commandId: 'logo:tool-ellipse',
    title: 'Use Oval Tool',
    description: 'Switch Logo Designer to circle and ellipse drawing mode.',
    category: 'tool',
    keywords: ['circle', 'ellipse', 'oval', 'draw shape', 'logo component'],
    shortcut: 'O',
  },
  {
    commandId: 'logo:tool-line',
    title: 'Use Line Tool',
    description: 'Switch Logo Designer to line drawing mode.',
    category: 'tool',
    keywords: ['line', 'stroke', 'draw line', 'logo component'],
    shortcut: 'L',
  },
  {
    commandId: 'logo:tool-text',
    title: 'Use Text Tool',
    description: 'Switch Logo Designer to text placement mode.',
    category: 'tool',
    keywords: ['text', 'label', 'word', 'type', 'logo component'],
    shortcut: 'T',
  },
  {
    commandId: 'logo:reset-components',
    title: 'Reset Logo Components',
    description: 'Remove all structured rectangle, oval, line, and text components from the active logo.',
    category: 'edit',
    keywords: ['reset', 'clear components', 'delete shapes', 'logo drawing'],
    dangerous: true,
  },
  {
    commandId: 'logo:toggle-inspect-mode',
    title: 'Toggle Logo Element Inspector',
    description: 'Show or hide the geometry overlay used while editing logo elements.',
    category: 'tool',
    keywords: ['inspect', 'element', 'geometry', 'overlay', 'logo edit tools'],
  },
  {
    commandId: 'logo:reset-element-edits',
    title: 'Reset Logo Element Edits',
    description: 'Clear direct element move, rotate, and scale edits for the active logo template.',
    category: 'edit',
    keywords: ['reset', 'clear edits', 'element offsets', 'direct editing', 'logo transform'],
  },
  {
    commandId: 'logo:animate-selected-variant',
    title: 'Animate Selected Logo Variant',
    description: 'Send the selected Logo Designer variant or morph pair to Preframe for animation and rendering.',
    category: 'tool',
    keywords: ['animate', 'motion', 'preframe', 'render', 'logo animation', 'variant morph'],
  },
];
