import type { AppIntent } from '../../index';

export const shellIntents: AppIntent[] = [
  {
    commandId: 'shell:settings',
    title: 'Open Settings',
    description: 'Open the Hudson settings panel to configure preferences.',
    category: 'settings',
    keywords: ['settings', 'preferences', 'config', 'options', 'configure'],
    shortcut: 'Cmd+,',
  },
  {
    commandId: 'shell:environment',
    title: 'Open Environment',
    description: 'Open Hudson’s environment panel to manage local .env.local variables.',
    category: 'settings',
    keywords: ['environment', 'env', '.env', '.env.local', 'variables', 'secrets'],
  },
  {
    commandId: 'shell:workspace-editor',
    title: 'Open Workspace Editor',
    description: 'Open the workspace editor to manage apps, services, and layout.',
    category: 'workspace',
    keywords: ['workspace editor', 'manage apps', 'workspace manager', 'services', 'layout'],
    shortcut: 'Cmd+Shift+,',
  },
  {
    commandId: 'shell:toggle-left',
    title: 'Toggle Left Panel',
    description: 'Show or hide the left sidebar navigation panel.',
    category: 'view',
    keywords: ['left panel', 'sidebar', 'navigation panel', 'toggle sidebar', 'left sidebar'],
    shortcut: 'Cmd+[',
  },
  {
    commandId: 'shell:toggle-right',
    title: 'Toggle Right Panel',
    description: 'Show or hide the right sidebar inspector panel.',
    category: 'view',
    keywords: ['right panel', 'inspector', 'right sidebar', 'toggle inspector', 'properties'],
    shortcut: 'Cmd+]',
  },
  {
    commandId: 'shell:toggle-terminal',
    title: 'Toggle Terminal',
    description: 'Show or hide the bottom terminal drawer.',
    category: 'view',
    keywords: ['terminal', 'console', 'bottom panel', 'drawer', 'command line'],
    shortcut: 'Ctrl+`',
  },
  {
    commandId: 'shell:start-voice',
    title: 'Start Voice Prompt',
    description: 'Open Hudson AI and start recording a voice prompt with Vox.',
    category: 'tool',
    keywords: ['voice', 'microphone', 'dictation', 'speech', 'record', 'vox'],
  },
  {
    commandId: 'shell:toggle-guides',
    title: 'Toggle Crosshair Guides',
    description: 'Show or hide crosshair alignment guides on the canvas.',
    category: 'view',
    keywords: ['guides', 'crosshair', 'alignment', 'rulers', 'crosshairs'],
    shortcut: 'Cmd+\\',
  },
  {
    commandId: 'shell:toggle-minimap',
    title: 'Toggle Minimap',
    description: 'Show or hide the minimap overview in the bottom-left corner.',
    category: 'view',
    keywords: ['minimap', 'overview', 'map', 'mini map', 'bird eye'],
  },
  {
    commandId: 'shell:reset-view',
    title: 'Reset View',
    description: 'Reset the canvas pan and zoom back to the default position.',
    category: 'navigation',
    keywords: ['reset view', 'reset zoom', 'home', 'default view', 'recenter'],
    shortcut: 'Cmd+0',
  },
  {
    commandId: 'shell:reset-all-windows',
    title: 'Reset All Windows',
    description: 'Reset all app windows to their default size and position.',
    category: 'workspace',
    keywords: ['reset windows', 'restore layout', 'default layout', 'reset positions'],
  },
  {
    commandId: 'shell:auto-layout',
    title: 'Auto Layout Windows',
    description: 'Arrange all visible windows into a clean grid layout and fit them into view.',
    category: 'workspace',
    keywords: ['auto layout', 'tile windows', 'arrange windows', 'grid layout', 'fit all'],
  },
  {
    commandId: 'shell:toggle-mute',
    title: 'Toggle Sound',
    description: 'Mute or unmute all UI sounds in Hudson.',
    category: 'toggle',
    keywords: ['mute', 'unmute', 'sound', 'audio', 'silence', 'volume'],
    shortcut: 'Cmd+M',
  },
];
