#!/usr/bin/env node
/**
 * snapshot-chunks.mjs
 *
 * Run after `bun run build` (which places the Next.js build in .next/ and the
 * static export in site/out/). Reads the build manifests + client-reference
 * manifest to discover the exact chunk URLs that the embed page loads, and
 * writes them to embed-worker/src/chunks.json.
 *
 * The Worker imports this file so it can reference the correct hashed URLs.
 *
 * Usage (from repo root):
 *   node embed-worker/scripts/snapshot-chunks.mjs
 * Or via the npm script:
 *   bun run embed:snapshot
 */

import { readFile, writeFile } from 'node:fs/promises';
import { existsSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dir = dirname(fileURLToPath(import.meta.url));
const root = join(__dir, '..', '..');
const nextDir = join(root, '.next');
const outDir = join(root, 'site', 'out');

// ── 1. Read the main build manifest ──────────────────────────────────────────
const buildManifest = JSON.parse(
  await readFile(join(nextDir, 'build-manifest.json'), 'utf-8'),
);

const rootChunks = [
  ...(buildManifest.polyfillFiles ?? []),
  ...(buildManifest.rootMainFiles ?? []),
];

// ── 2. Read the embed page's build manifest ───────────────────────────────────
const embedPageManifestPath = join(
  nextDir,
  'server/app/embed/[appId]/[surface]/page/build-manifest.json',
);

let embedPageChunks = [];
if (existsSync(embedPageManifestPath)) {
  const embedManifest = JSON.parse(await readFile(embedPageManifestPath, 'utf-8'));
  embedPageChunks = [
    ...(embedManifest.polyfillFiles ?? []),
    ...(embedManifest.rootMainFiles ?? []),
  ];
}

// ── 3. Extract client chunks from client-reference-manifest ──────────────────
// These are the dynamically-loaded chunks for EmbedHandshake, EmbedWorkspace,
// WorkspaceShell, etc. Next.js normally injects these via RSC streaming.
// We need to include them explicitly in the Worker's static HTML.
const clientRefManifestPath = join(
  nextDir,
  'server/app/embed/[appId]/[surface]/page_client-reference-manifest.js',
);

let clientRefChunks = [];
if (existsSync(clientRefManifestPath)) {
  const raw = await readFile(clientRefManifestPath, 'utf-8');
  // Extract all "/_next/static/chunks/..." paths from the manifest
  const matches = raw.matchAll(/"\/\_next\/static\/chunks\/[a-f0-9]+\.js"/g);
  const seen = new Set();
  for (const [m] of matches) {
    const path = m.slice(1, -1); // strip quotes
    if (!seen.has(path)) {
      seen.add(path);
      clientRefChunks.push(path);
    }
  }
}

// ── 4. Find the CSS files in site/out/_next/static/chunks/ ───────────────────
const chunksDir = join(outDir, '_next', 'static', 'chunks');
let cssFiles = [];
if (existsSync(chunksDir)) {
  cssFiles = readdirSync(chunksDir)
    .filter(f => f.endsWith('.css'))
    .map(f => `/_next/static/chunks/${f}`);
}

// ── 5. Find the build hash (the versioned directory under static/) ────────────
const staticDir = join(outDir, '_next', 'static');
let buildHash = '';
if (existsSync(staticDir)) {
  const entries = readdirSync(staticDir, { withFileTypes: true });
  const hashDir = entries.find(
    e => e.isDirectory() && !['chunks', 'media', 'css'].includes(e.name),
  );
  if (hashDir) buildHash = hashDir.name;
}

// ── 6. Compose the full script list ──────────────────────────────────────────
// Order: polyfill → runtime → page-level → client-ref chunks
const runtimeScripts = [...new Set([...rootChunks, ...embedPageChunks])].map(
  c => (c.startsWith('/') ? c : `/_next/${c}`),
);

// Client-ref chunks come after runtime (they depend on it)
const allScripts = [...new Set([...runtimeScripts, ...clientRefChunks])];

// ── 7. Write chunks.json ─────────────────────────────────────────────────────
const output = {
  _comment: 'Auto-generated by embed-worker/scripts/snapshot-chunks.mjs — DO NOT EDIT',
  buildHash,
  scripts: allScripts,
  styles: cssFiles,
};

const outFile = join(__dir, '..', 'src', 'chunks.json');
await writeFile(outFile, JSON.stringify(output, null, 2) + '\n');

console.log(`[snapshot-chunks] Written → ${outFile}`);
console.log(`  Build hash : ${buildHash || '(not found)'}`);
console.log(`  Scripts    : ${allScripts.length} (${runtimeScripts.length} runtime + ${clientRefChunks.length} client-ref)`);
console.log(`  Styles     : ${cssFiles.length}`);
