import type { AppIntent } from '@hudson/sdk';

export const shellIntents: AppIntent[] = [
  {
    commandId: 'shell:settings',
    title: 'Open Settings',
    description: 'Open the Hudson settings panel to configure preferences.',
    category: 'settings',
    keywords: ['settings', 'preferences', 'config', 'options', 'configure'],
    shortcut: 'Cmd+,',
  },
  {
    commandId: 'shell:toggle-left',
    title: 'Toggle Left Panel',
    description: 'Show or hide the left sidebar navigation panel.',
    category: 'view',
    keywords: ['left panel', 'sidebar', 'navigation panel', 'toggle sidebar', 'left sidebar'],
    shortcut: 'Cmd+[',
  },
  {
    commandId: 'shell:toggle-right',
    title: 'Toggle Right Panel',
    description: 'Show or hide the right sidebar inspector panel.',
    category: 'view',
    keywords: ['right panel', 'inspector', 'right sidebar', 'toggle inspector', 'properties'],
    shortcut: 'Cmd+]',
  },
  {
    commandId: 'shell:toggle-terminal',
    title: 'Toggle Terminal',
    description: 'Show or hide the bottom terminal drawer.',
    category: 'view',
    keywords: ['terminal', 'console', 'bottom panel', 'drawer', 'command line'],
    shortcut: 'Ctrl+`',
  },
  {
    commandId: 'shell:toggle-guides',
    title: 'Toggle Crosshair Guides',
    description: 'Show or hide crosshair alignment guides on the canvas.',
    category: 'view',
    keywords: ['guides', 'crosshair', 'alignment', 'rulers', 'crosshairs'],
    shortcut: 'Cmd+\\',
  },
  {
    commandId: 'shell:toggle-minimap',
    title: 'Toggle Minimap',
    description: 'Show or hide the minimap overview in the bottom-left corner.',
    category: 'view',
    keywords: ['minimap', 'overview', 'map', 'mini map', 'bird eye'],
  },
  {
    commandId: 'shell:reset-view',
    title: 'Reset View',
    description: 'Reset the canvas pan and zoom back to the default position.',
    category: 'navigation',
    keywords: ['reset view', 'reset zoom', 'home', 'default view', 'recenter'],
    shortcut: 'Cmd+0',
  },
  {
    commandId: 'shell:reset-all-windows',
    title: 'Reset All Windows',
    description: 'Reset all app windows to their default size and position.',
    category: 'workspace',
    keywords: ['reset windows', 'restore layout', 'default layout', 'reset positions'],
  },
  {
    commandId: 'shell:toggle-mute',
    title: 'Toggle Sound',
    description: 'Mute or unmute all UI sounds in Hudson.',
    category: 'toggle',
    keywords: ['mute', 'unmute', 'sound', 'audio', 'silence', 'volume'],
    shortcut: 'Cmd+M',
  },
];
