/**
 * Built-in template definitions.
 * Each entry has a renderBody (JS function body), name, and description.
 * Used to seed the template store on first load.
 *
 * AUTO-GENERATED by scripts/reverse-seed.ts — do not edit manually.
 * Edit the .data/logo-templates/*.js files and re-run:
 *   bun scripts/reverse-seed.ts
 */

export interface BuiltinDef {
  name: string;
  description: string;
  renderBody: string;
  params?: Record<string, unknown>;
}

const negativeSpace: BuiltinDef = {
  name: 'Negative Space',
  description: 'White panes on dark bg. L-shape formed by the gap.',
  renderBody: `\
const { bgColor, paneColor, dimPaneColor, borderRadius, paneRadius, gapWidth, splitX, splitY, padding } = p;
const content = vb - padding * 2;
const vGap = padding + content * splitX;
const hGap = padding + content * splitY;
const leftW = vGap - padding;
const rightX = vGap + gapWidth;
const rightW = vb - padding - rightX;
const topH = hGap - padding;
const bottomY = hGap + gapWidth;
const bottomH = vb - padding - bottomY;
const uid = 'ns' + Math.random().toString(36).slice(2, 6);

let svg = \`<defs>
<linearGradient id="dp-\${uid}" x1="0" y1="0" x2="0" y2="1">
<stop offset="0" stop-color="black" stop-opacity="0"/>
<stop offset="1" stop-color="black" stop-opacity="0.04"/>
</linearGradient>
</defs>\`;

svg += \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>\`;

// Soft ambient glow behind the L-channel
const g1 = 8;
svg += \`<rect x="\${vGap - g1}" y="\${padding - g1}" width="\${gapWidth + g1 * 2}" height="\${content + g1 * 2}" rx="\${gapWidth / 2 + g1}" fill="\${paneColor}" opacity="0.02"/>\`;
svg += \`<rect x="\${padding - g1}" y="\${hGap - g1}" width="\${content + g1 * 2}" height="\${gapWidth + g1 * 2}" rx="\${gapWidth / 2 + g1}" fill="\${paneColor}" opacity="0.02"/>\`;
const g2 = 3;
svg += \`<rect x="\${vGap - g2}" y="\${padding - g2}" width="\${gapWidth + g2 * 2}" height="\${content + g2 * 2}" rx="\${gapWidth / 2 + g2}" fill="\${paneColor}" opacity="0.035"/>\`;
svg += \`<rect x="\${padding - g2}" y="\${hGap - g2}" width="\${content + g2 * 2}" height="\${gapWidth + g2 * 2}" rx="\${gapWidth / 2 + g2}" fill="\${paneColor}" opacity="0.035"/>\`;

// Main panes — L-shape: left column + bottom row
svg += \`<rect x="\${padding}" y="\${padding}" width="\${leftW}" height="\${content}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;
svg += \`<rect x="\${rightX}" y="\${padding}" width="\${rightW}" height="\${topH}" rx="\${paneRadius}" fill="\${dimPaneColor}"/>\`;
svg += \`<rect x="\${padding}" y="\${bottomY}" width="\${content}" height="\${bottomH}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;

// Subtle depth gradient on L-panes
svg += \`<rect x="\${padding}" y="\${padding}" width="\${leftW}" height="\${content}" rx="\${paneRadius}" fill="url(#dp-\${uid})"/>\`;
svg += \`<rect x="\${padding}" y="\${bottomY}" width="\${content}" height="\${bottomH}" rx="\${paneRadius}" fill="url(#dp-\${uid})"/>\`;

return svg;`,
};

const greenChannel: BuiltinDef = {
  name: 'Green Channel',
  description: 'Dark panes with glowing translucent channel forming the L.',
  renderBody: `\
const { bgColor, paneColor, channelColor, borderRadius, paneRadius, gapWidth, splitX, splitY, padding } = p;
const content = vb - padding * 2;
const vGap = padding + content * splitX;
const hGap = padding + content * splitY;
const rightX = vGap + gapWidth;
const rightW = vb - padding - rightX;
const topH = hGap - padding;
const bottomY = hGap + gapWidth;
const bottomH = vb - padding - bottomY;
const leftW = vGap - padding;

let svg = \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>\`;

// Outer channel glow (wide, faint)
const g1 = 10;
svg += \`<rect x="\${vGap - g1}" y="\${padding}" width="\${gapWidth + g1 * 2}" height="\${topH}" rx="\${gapWidth / 2 + g1}" fill="\${channelColor}" opacity="0.08"/>\`;
svg += \`<rect x="\${vGap - g1}" y="\${hGap}" width="\${gapWidth + g1 * 2}" height="\${gapWidth}" rx="\${gapWidth / 2 + g1}" fill="\${channelColor}" opacity="0.08"/>\`;
svg += \`<rect x="\${rightX}" y="\${hGap - g1}" width="\${rightW}" height="\${gapWidth + g1 * 2}" rx="\${gapWidth / 2 + g1}" fill="\${channelColor}" opacity="0.08"/>\`;

// Inner channel glow (tighter, brighter)
const g2 = 4;
svg += \`<rect x="\${vGap - g2}" y="\${padding}" width="\${gapWidth + g2 * 2}" height="\${topH}" rx="\${gapWidth / 2 + g2}" fill="\${channelColor}" opacity="0.15"/>\`;
svg += \`<rect x="\${vGap - g2}" y="\${hGap - g2}" width="\${gapWidth + g2 * 2}" height="\${gapWidth + g2 * 2}" rx="\${gapWidth / 2 + g2}" fill="\${channelColor}" opacity="0.15"/>\`;
svg += \`<rect x="\${rightX}" y="\${hGap - g2}" width="\${rightW}" height="\${gapWidth + g2 * 2}" rx="\${gapWidth / 2 + g2}" fill="\${channelColor}" opacity="0.15"/>\`;

// Intersection hotspot — brighter where L-arms meet
svg += \`<rect x="\${vGap - 2}" y="\${hGap - 2}" width="\${gapWidth + 4}" height="\${gapWidth + 4}" rx="\${gapWidth / 2 + 2}" fill="\${channelColor}" opacity="0.12"/>\`;

// Dark panes
svg += \`<rect x="\${padding}" y="\${padding}" width="\${leftW}" height="\${content}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;
svg += \`<rect x="\${rightX}" y="\${padding}" width="\${rightW}" height="\${topH}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;
svg += \`<rect x="\${padding}" y="\${bottomY}" width="\${content}" height="\${bottomH}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;

// Channel lines (the actual visible L)
svg += \`<rect x="\${vGap}" y="\${padding}" width="\${gapWidth}" height="\${topH}" rx="2" fill="\${channelColor}"/>\`;
svg += \`<rect x="\${vGap}" y="\${hGap}" width="\${gapWidth}" height="\${gapWidth}" rx="2" fill="\${channelColor}"/>\`;
svg += \`<rect x="\${rightX}" y="\${hGap}" width="\${rightW}" height="\${gapWidth}" rx="2" fill="\${channelColor}"/>\`;

return svg;`,
};

const gridColor: BuiltinDef = {
  name: 'Grid Color',
  description: '2x2 grid. Three L-quadrants filled, one ghosted.',
  renderBody: `\
const { bgColor, paneColor, dimPaneColor, borderRadius, paneRadius, gapWidth, padding } = p;
const uid = 'gc' + Math.random().toString(36).slice(2, 6);
const content = vb - padding * 2;
const cell = (content - gapWidth) / 2;
const x1 = padding;
const y1 = padding;
const x2 = padding + cell + gapWidth;
const y2 = padding + cell + gapWidth;

let svg = \`<defs>
<linearGradient id="gp-\${uid}" x1="0" y1="0" x2="0" y2="1">
<stop offset="0" stop-color="black" stop-opacity="0"/>
<stop offset="1" stop-color="black" stop-opacity="0.035"/>
</linearGradient>
</defs>\`;

svg += \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>\`;

// L-quadrants — top-left, bottom-left, bottom-right (solid fills)
svg += \`<rect x="\${x1}" y="\${y1}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;
svg += \`<rect x="\${x1}" y="\${y2}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;
svg += \`<rect x="\${x2}" y="\${y2}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="\${paneColor}"/>\`;

// Depth gradient on L-quadrants
svg += \`<rect x="\${x1}" y="\${y1}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="url(#gp-\${uid})"/>\`;
svg += \`<rect x="\${x1}" y="\${y2}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="url(#gp-\${uid})"/>\`;
svg += \`<rect x="\${x2}" y="\${y2}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="url(#gp-\${uid})"/>\`;

// Ghost quadrant — top-right (outline only)
svg += \`<rect x="\${x2 + 0.5}" y="\${y1 + 0.5}" width="\${cell - 1}" height="\${cell - 1}" rx="\${Math.max(0, paneRadius - 0.5)}" fill="none" stroke="\${dimPaneColor}" stroke-width="1"/>\`;

// Subtle intersection accent
const cx = padding + cell + gapWidth / 2;
const cy = padding + cell + gapWidth / 2;
svg += \`<circle cx="\${cx}" cy="\${cy}" r="\${Math.min(gapWidth * 0.25, 4)}" fill="\${paneColor}" opacity="0.12"/>\`;

return svg;`,
};

const interlocking: BuiltinDef = {
  name: 'Interlocking',
  description: 'Two interlocking L-shaped pieces with subtle depth.',
  renderBody: `\
const { bgColor, paneColor, borderRadius, gapWidth, padding } = p;
const notchR = Number(p.notchRatio) || 0.5;
const secOp = Number(p.secondaryOpacity) || 0.50;
const content = vb - padding * 2;
const cell = (content - gapWidth) / 2;
const notch = cell * notchR;
const arm = cell - notch;
const x1 = padding, x2 = padding + cell + gapWidth;
const y1 = padding, y2 = padding + cell + gapWidth;
const nx = x1 + arm, ny = y1 + arm;
const nx2 = x2 + notch, ny2 = y2 + notch;

let svg = \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>\`;

const p1 = \`M\${x1},\${y1} H\${x1 + cell} V\${ny} H\${nx} V\${y1 + cell} H\${x1} Z\`;
const p2 = \`M\${x2},\${y1} H\${x2 + cell} V\${y1 + cell} H\${nx2} V\${ny} H\${x2} Z\`;
const p3 = \`M\${x1},\${y2} H\${nx} V\${ny2} H\${x1 + cell} V\${y2 + cell} H\${x1} Z\`;
const p4 = \`M\${nx2},\${y2} H\${x2 + cell} V\${y2 + cell} H\${x2} V\${ny2} H\${nx2} Z\`;

svg += \`<path d="\${p1}" fill="black" opacity="0.06" transform="translate(1.5, 1.5)"/>\`;
svg += \`<path d="\${p3}" fill="black" opacity="0.06" transform="translate(1.5, 1.5)"/>\`;

svg += \`<path d="\${p1}" fill="\${paneColor}"/>\`;
svg += \`<path d="\${p3}" fill="\${paneColor}"/>\`;

svg += \`<path d="\${p2}" fill="\${paneColor}" opacity="\${secOp}"/>\`;
svg += \`<path d="\${p4}" fill="\${paneColor}" opacity="\${secOp}"/>\`;

svg += \`<path d="\${p1}" fill="none" stroke="white" stroke-width="0.6" opacity="0.08"/>\`;
svg += \`<path d="\${p3}" fill="none" stroke="white" stroke-width="0.6" opacity="0.08"/>\`;

return svg;`,
  params: {
      "notchRatio": {
          "type": "number",
          "label": "Notch depth",
          "default": 0.5,
          "min": 0.2,
          "max": 0.8,
          "step": 0.05
      },
      "secondaryOpacity": {
          "type": "number",
          "label": "Secondary opacity",
          "default": 0.5,
          "min": 0.1,
          "max": 1,
          "step": 0.05
      }
  },
};

const latticeGrid: BuiltinDef = {
  name: 'Lattice Grid',
  description: 'NxN grid. L highlighted by color with subtle depth.',
  renderBody: `\
const { bgColor, paneColor, dimPaneColor, borderRadius, paneRadius, gapWidth, padding } = p;
const cols = Number(p.gridSize) || 3;
const glowPx = Number(p.glowSize) || 3;
const glowOp = Number(p.glowOpacity) || 0.04;
const content = vb - padding * 2;
const cellSize = (content - gapWidth * (cols - 1)) / cols;
const isL = (col, row) => col === 0 || row === cols - 1;

let svg = \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>\`;

// Faint glow behind L-cells
if (glowPx > 0) {
  for (let row = 0; row < cols; row++) {
    for (let col = 0; col < cols; col++) {
      if (!isL(col, row)) continue;
      const x = padding + col * (cellSize + gapWidth) - glowPx;
      const y = padding + row * (cellSize + gapWidth) - glowPx;
      svg += \`<rect x="\${x}" y="\${y}" width="\${cellSize + glowPx * 2}" height="\${cellSize + glowPx * 2}" rx="\${paneRadius + glowPx}" fill="\${paneColor}" opacity="\${glowOp}"/>\`;
    }
  }
}

// Grid cells
for (let row = 0; row < cols; row++) {
  for (let col = 0; col < cols; col++) {
    const x = padding + col * (cellSize + gapWidth);
    const y = padding + row * (cellSize + gapWidth);
    const inL = isL(col, row);
    svg += \`<rect x="\${x}" y="\${y}" width="\${cellSize}" height="\${cellSize}" rx="\${paneRadius}" fill="\${inL ? paneColor : dimPaneColor}"/>\`;
  }
}

// Tiny accent dots at grid intersections
const dotR = Math.min(gapWidth * 0.18, 2);
if (dotR > 0.5) {
  for (let row = 0; row < cols - 1; row++) {
    for (let col = 0; col < cols - 1; col++) {
      const cx = padding + (col + 1) * cellSize + col * gapWidth + gapWidth / 2;
      const cy = padding + (row + 1) * cellSize + row * gapWidth + gapWidth / 2;
      svg += \`<circle cx="\${cx}" cy="\${cy}" r="\${dotR}" fill="\${paneColor}" opacity="0.10"/>\`;
    }
  }
}

return svg;`,
  params: {
      "gridSize": {
          "type": "number",
          "label": "Grid size",
          "default": 3,
          "min": 2,
          "max": 6,
          "step": 1
      },
      "glowSize": {
          "type": "number",
          "label": "Glow spread",
          "default": 3,
          "min": 0,
          "max": 10,
          "step": 1
      },
      "glowOpacity": {
          "type": "number",
          "label": "Glow intensity",
          "default": 0.04,
          "min": 0,
          "max": 0.15,
          "step": 0.01
      }
  },
};

const appWindows: BuiltinDef = {
  name: 'App Windows',
  description: 'Four panes styled as macOS app windows forming L.',
  renderBody: `\
const { bgColor, borderRadius, paneRadius, gapWidth, padding } = p;
const content = vb - padding * 2;
const cell = (content - gapWidth) / 2;
const x1 = padding, y1 = padding;
const x2 = padding + cell + gapWidth, y2 = padding + cell + gapWidth;
const tb = 14, dr = 1.8, dg = 5.5, d0 = 8;
const lBg = '#2c2c2e', lTitle = 'rgba(255,255,255,0.10)';
const xBg = '#242440', xTitle = 'rgba(88,86,214,0.20)';
const uid = Math.random().toString(36).slice(2, 6);

function dots(cx, cy) {
  return \`<circle cx="\${cx+d0}" cy="\${cy}" r="\${dr}" fill="#ff5f57" opacity="0.8"/>
<circle cx="\${cx+d0+dg}" cy="\${cy}" r="\${dr}" fill="#ffbd2e" opacity="0.8"/>
<circle cx="\${cx+d0+dg*2}" cy="\${cy}" r="\${dr}" fill="#28ca42" opacity="0.8"/>\`;
}

function win(wx, wy, bg, titleFill, clipId, contentSvg) {
  // Subtle shadow behind window
  let s = \`<rect x="\${wx + 2}" y="\${wy + 2}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="black" opacity="0.12"/>\`;
  s += \`<g>
<rect x="\${wx}" y="\${wy}" width="\${cell}" height="\${cell}" rx="\${paneRadius}" fill="\${bg}"/>
<defs><clipPath id="\${clipId}"><rect x="\${wx}" y="\${wy}" width="\${cell}" height="\${cell}" rx="\${paneRadius}"/></clipPath></defs>
<g clip-path="url(#\${clipId})">
  <rect x="\${wx}" y="\${wy}" width="\${cell}" height="\${tb}" fill="\${titleFill}"/>
  <line x1="\${wx}" y1="\${wy+tb}" x2="\${wx+cell}" y2="\${wy+tb}" stroke="rgba(255,255,255,0.04)" stroke-width="0.5"/>
</g>
\${dots(wx, wy+tb/2)}
\${contentSvg}
</g>\`;
  return s;
}

const iterm = Array.from({length:5}, (_,i) => {
  const widths = [0.55,0.35,0.65,0.45,0.5];
  const ops = [0.65,0.45,0.35,0.5,0.4];
  return \`<rect x="\${x1+8}" y="\${y1+tb+10+i*9}" width="\${cell*widths[i]}" height="3" rx="1" fill="rgba(51,199,115,\${ops[i]})"/>\`;
}).join('');

const preview = \`<rect x="\${x1+cell*0.15}" y="\${y2+tb+cell*0.1}" width="\${cell*0.7}" height="\${cell*0.55}" rx="4" fill="rgba(255,255,255,0.08)"/>
<rect x="\${x1+cell*0.3}" y="\${y2+tb+cell*0.25}" width="\${cell*0.4}" height="\${cell*0.2}" rx="3" fill="rgba(255,255,255,0.12)"/>\`;

const chrome = \`<rect x="\${x2+8}" y="\${y2+tb+8}" width="\${cell-16}" height="9" rx="4.5" fill="rgba(255,255,255,0.10)"/>
\${[0.7,0.5,0.6,0.45].map((w,i) => \`<rect x="\${x2+8}" y="\${y2+tb+26+i*9}" width="\${cell*w}" height="3" rx="1" fill="rgba(255,255,255,\${0.15-i*0.02})"/>\`).join('')}\`;

const xcode = [0.4,0.55,0.35,0.4,0.5,0.3].map((w,i) => {
  const indent = [8,16,16,24,16,8][i];
  const ops = [0.55,0.35,0.40,0.30,0.35,0.50][i];
  return \`<rect x="\${x2+indent}" y="\${y1+tb+10+i*9}" width="\${cell*w}" height="3" rx="1" fill="rgba(120,118,240,\${ops})"/>\`;
}).join('');

return \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>
\${win(x1,y1,lBg,lTitle,'aw-tl-'+uid,iterm)}
\${win(x1,y2,lBg,lTitle,'aw-bl-'+uid,preview)}
\${win(x2,y2,lBg,lTitle,'aw-br-'+uid,chrome)}
\${win(x2,y1,xBg,xTitle,'aw-tr-'+uid,xcode)}\`;`,
};

const dotMatrix: BuiltinDef = {
  name: 'Dot Matrix',
  description: 'Stippled dot field. L-shape emerges from density and brightness.',
  renderBody: `\
const { bgColor, paneColor, dimPaneColor, borderRadius, splitX, splitY, padding } = p;
const step = Number(p.dotSpacing) || 12;
const base = Number(p.dotSize) || 2.4;
const decay = Number(p.falloffRate) || 0.35;
const content = vb - padding * 2;
const cols = Math.floor(content / step) + 1;
const rows = Math.floor(content / step) + 1;
const ox = padding + (content - (cols - 1) * step) / 2;
const oy = padding + (content - (rows - 1) * step) / 2;
const sC = Math.round(cols * splitX);
const sR = Math.round(rows * splitY);

function hash(a, b) {
  let n = ((a * 2654435761) ^ (b * 2246822519)) >>> 0;
  n = ((n >> 16) ^ n) >>> 0;
  return (n % 1000) / 1000;
}

let svg = \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>\`;

for (let r = 0; r < rows; r++) {
  for (let c = 0; c < cols; c++) {
    const cx = (ox + c * step).toFixed(1);
    const cy = (oy + r * step).toFixed(1);
    const inL = c < sC || r >= sR;

    const dCol = c < sC ? 0 : c - sC;
    const dRow = r >= sR ? 0 : sR - r;
    const dToL = inL ? 0 : Math.min(dCol, dRow);

    const falloff = Math.exp(-dToL * decay);
    const h = hash(c, r);
    const jitter = 0.85 + h * 0.3;

    let dr, op, fill;
    if (inL) {
      dr = base * (0.9 + h * 0.25) * jitter;
      op = 0.65 + h * 0.25;
      fill = paneColor;
    } else {
      dr = base * 0.45 * falloff * jitter + base * 0.2;
      op = 0.15 + 0.55 * falloff;
      fill = falloff > 0.5 ? paneColor : dimPaneColor;
    }

    svg += \`<circle cx="\${cx}" cy="\${cy}" r="\${dr.toFixed(2)}" fill="\${fill}" opacity="\${op.toFixed(2)}"/>\`;
  }
}
return svg;`,
  params: {
      "dotSpacing": {
          "type": "number",
          "label": "Dot spacing",
          "default": 12,
          "min": 6,
          "max": 24,
          "step": 1
      },
      "dotSize": {
          "type": "number",
          "label": "Dot size",
          "default": 2.4,
          "min": 1,
          "max": 5,
          "step": 0.1
      },
      "falloffRate": {
          "type": "number",
          "label": "Edge falloff",
          "default": 0.35,
          "min": 0.1,
          "max": 1,
          "step": 0.05
      }
  },
};

const mosaic: BuiltinDef = {
  name: 'Mosaic',
  description: 'Dissolving tile grid. L emerges through size and opacity falloff.',
  renderBody: `\
const { bgColor, paneColor, dimPaneColor, borderRadius, paneRadius, gapWidth, padding } = p;
const cols = Number(p.gridSize) || 5;
const curve = Number(p.falloffCurve) || 1.8;
const minSc = Number(p.minScale) || 0.15;
const content = vb - padding * 2;
const cellSize = (content - gapWidth * (cols - 1)) / cols;
const maxR = Math.min(paneRadius, cellSize / 2);

function dist(col, row) {
  const dCol = col;
  const dRow = (cols - 1) - row;
  return Math.min(dCol, dRow);
}

const maxDist = cols - 1;

let svg = \`<rect width="\${vb}" height="\${vb}" rx="\${borderRadius}" fill="\${bgColor}"/>\`;

for (let row = 0; row < cols; row++) {
  for (let col = 0; col < cols; col++) {
    const cx = padding + col * (cellSize + gapWidth) + cellSize / 2;
    const cy = padding + row * (cellSize + gapWidth) + cellSize / 2;
    const d = dist(col, row);

    if (d === 0) {
      const x = cx - cellSize / 2;
      const y = cy - cellSize / 2;
      svg += \`<rect x="\${x - 3}" y="\${y - 3}" width="\${cellSize + 6}" height="\${cellSize + 6}" rx="\${maxR + 3}" fill="\${paneColor}" opacity="0.05"/>\`;
      svg += \`<rect x="\${x}" y="\${y}" width="\${cellSize}" height="\${cellSize}" rx="\${maxR}" fill="\${paneColor}"/>\`;
    } else {
      const t = d / maxDist;
      const scale = Math.max(minSc, Math.pow(1 - t, curve));
      const opacity = Math.max(0.04, Math.pow(1 - t, curve + 0.2));
      const s = cellSize * scale;
      const x = cx - s / 2;
      const y = cy - s / 2;
      const sr = Math.min(maxR * (1 + d * 0.35), s / 2);
      svg += \`<rect x="\${x}" y="\${y}" width="\${s}" height="\${s}" rx="\${sr}" fill="\${dimPaneColor}" opacity="\${opacity.toFixed(2)}"/>\`;
    }
  }
}
return svg;`,
  params: {
      "gridSize": {
          "type": "number",
          "label": "Grid size",
          "default": 5,
          "min": 3,
          "max": 8,
          "step": 1
      },
      "falloffCurve": {
          "type": "number",
          "label": "Falloff curve",
          "default": 1.8,
          "min": 0.5,
          "max": 4,
          "step": 0.1
      },
      "minScale": {
          "type": "number",
          "label": "Min tile scale",
          "default": 0.15,
          "min": 0,
          "max": 0.5,
          "step": 0.05
      }
  },
};

export const builtinRenderBodies: Record<string, BuiltinDef> = {
  'negative-space': negativeSpace,
  'green-channel': greenChannel,
  'grid-color': gridColor,
  'interlocking': interlocking,
  'lattice-grid': latticeGrid,
  'app-windows': appWindows,
  'dot-matrix': dotMatrix,
  'mosaic': mosaic,
};
