/**
 * Reverse-seed: read .data/logo-templates/*.js and regenerate builtinRenderBodies.ts
 * Run: bun scripts/reverse-seed.ts
 */
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const SEED_DIR = join(import.meta.dirname, '..', '.data', 'logo-templates');
const OUT = join(import.meta.dirname, '..', 'app', 'apps', 'logo', 'builtinRenderBodies.ts');

const builtins = [
  'negative-space', 'green-channel', 'grid-color', 'interlocking',
  'lattice-grid', 'app-windows', 'dot-matrix', 'mosaic', 't-decoration',
];

let ts = `/**
 * Built-in template definitions.
 * Each entry has a renderBody (JS function body), name, and description.
 * Used to seed the template store on first load.
 *
 * AUTO-GENERATED by scripts/reverse-seed.ts — do not edit manually.
 * Edit the .data/logo-templates/*.js files and re-run:
 *   bun scripts/reverse-seed.ts
 */

export interface BuiltinDef {
  name: string;
  description: string;
  renderBody: string;
  params?: Record<string, unknown>;
}

`;

for (const id of builtins) {
  const source = readFileSync(join(SEED_DIR, `${id}.js`), 'utf-8');

  // Extract meta
  const metaMatch = source.match(/const\s+meta\s*=\s*(\{[\s\S]*?\});/);
  if (!metaMatch) throw new Error(`No meta found in ${id}.js`);
  // eslint-disable-next-line no-new-func
  const meta = new Function(`return ${metaMatch[0].replace('const meta = ', '').replace(/;$/, '')}`)();

  // Extract renderBody — everything after the meta block
  const metaEnd = (metaMatch.index ?? 0) + metaMatch[0].length;
  const renderBody = source.slice(metaEnd).replace(/^\n+/, '').trimEnd();

  // Escape for TypeScript template literal
  const escaped = renderBody
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');

  const varName = id.replace(/-(.)/g, (_, c: string) => c.toUpperCase());
  const descEscaped = (meta.description || '').replace(/'/g, "\\'");

  ts += `const ${varName}: BuiltinDef = {\n`;
  ts += `  name: '${meta.name}',\n`;
  ts += `  description: '${descEscaped}',\n`;
  ts += `  renderBody: \`\\\n${escaped}\`,\n`;
  if (meta.params) {
    ts += `  params: ${JSON.stringify(meta.params, null, 4).replace(/\n/g, '\n  ')},\n`;
  }
  ts += `};\n\n`;
}

ts += `export const builtinRenderBodies: Record<string, BuiltinDef> = {\n`;
for (const id of builtins) {
  const varName = id.replace(/-(.)/g, (_, c: string) => c.toUpperCase());
  ts += `  '${id}': ${varName},\n`;
}
ts += `};\n`;

writeFileSync(OUT, ts);
console.log(`Wrote ${OUT}`);
