import {chromium} from 'playwright';
import {pathToFileURL} from 'node:url';
import type {createMockTransport} from './mock';
declare global {var editorMock:ReturnType<typeof createMockTransport>;}
const browser=await chromium.launch({executablePath:process.env.EDITOR_BROWSER_EXECUTABLE??'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const assert=(x:unknown,m:string)=>{if(!x)throw Error(m);};
try{const page=await browser.newPage({viewport:{width:1280,height:1340},reducedMotion:'reduce'});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(import.meta.dir+'/dist-dev/index.html').href+'?mock&host&act');await page.getByRole('heading',{name:'Lattices',exact:true}).waitFor();await page.evaluate(()=>document.fonts.ready);await page.locator('[aria-label="Development mock controls"]').evaluate(el=>(el as HTMLElement).style.display='none');
 const mutations=()=>page.evaluate(()=>editorMock.calls.filter(k=>['action.plan','action.confirm','action.undo','action.reveal'].includes(k)));
 assert((await mutations()).length===0,'No action on load');await page.evaluate(()=>{editorMock.command({command:'selectLayers',value:['fab']});editorMock.command({command:'view',value:'workspace'});editorMock.command({command:'view',value:'overview'});editorMock.command({command:'selectLayers',value:['lattices']});});assert((await mutations()).length===0,'No action on selection or view changes');
 const input=page.getByRole('textbox',{name:'Message about this layer'});await input.fill('Why is Notes missing?');await input.press('Meta+Enter');await page.getByText('Open Notes',{exact:true}).last().waitFor();await page.waitForFunction(()=>!document.querySelector('.assistant-typing'));assert((await mutations()).length===0,'Assistant response/suggestions never act');
 await page.screenshot({path:import.meta.dir+'/design-evidence/act-layer-1280.png'});
 await page.getByRole('button',{name:/Gather windows/}).first().click();await page.getByRole('dialog').waitFor();await page.getByRole('heading',{name:'Gather Lattices?'}).waitFor();assert((await mutations()).join(',')==='action.plan','First click plans only');await page.screenshot({path:import.meta.dir+'/design-evidence/act-confirm-1280.png'});
 await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});assert(!(await mutations()).includes('action.confirm'),'Escape cancels');
 await page.getByRole('button',{name:/Gather windows/}).first().click();await page.getByRole('heading',{name:'Gather Lattices?'}).waitFor();await page.getByRole('button',{name:'Gather',exact:true}).click();await page.getByText('Gathered 3 windows and put 6 away',{exact:false}).waitFor();await page.getByText('In place',{exact:true}).waitFor();await page.getByRole('button',{name:'Undo',exact:true}).waitFor();assert((await mutations()).filter(k=>k==='action.confirm').length===1,'Exactly one confirmation');
 await page.locator('.overview-content').evaluate(el=>el.scrollTop=0);await page.screenshot({path:import.meta.dir+'/design-evidence/act-done-1280.png'});
 await input.fill('draft');await input.press('Meta+z');assert(!(await mutations()).includes('action.undo'),'Composer owns undo');await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByText('Undid gather · restored 9, skipped 1 (you moved Ghostty since).',{exact:false}).waitFor();await page.screenshot({path:import.meta.dir+'/design-evidence/act-undo-1280.png'});assert((await mutations()).filter(k=>k==='action.undo').length===1,'Undo only once');
 await page.getByRole('button',{name:'Details',exact:true}).click();assert(await page.getByRole('region',{name:'Recent actions'}).isVisible(),'History readable');assert(await page.locator('.action-history button').count()===0,'No older invalid Undo');
 await page.getByRole('button',{name:'Open Notes',exact:true}).first().click();await page.getByRole('dialog').waitFor();assert((await page.getByRole('dialog').innerText()).includes('No launch command'),'Open describes actual opening scope');await page.getByRole('button',{name:'Cancel',exact:true}).click();assert((await mutations()).filter(k=>k==='action.confirm').length===1,'Open cancelled without effects');
 assert(errors.length===0,errors.join('\n'));console.log('PASS Act: no effects on load/select/view/chat, confirm/cancel, receipt, native refresh, Undo/history, composer shortcut, Open scope');await page.close();}finally{await browser.close();}
