import type {HostEnvelope} from '../../packages/web/hudsonkit/src/editor/host-bridge';
import type {Projection} from './model';
import type {NativePlan} from './act-wire';
import type {ActResult,ActHistory,AssistantSnapshot} from './act-controller';
/** Development-only effects are mutations of this synthetic fixture, never native calls. */
export function createActMock(fixture:()=>{projection:Projection},emit:(kind:string,payload:object)=>void) {
 let sequence=0,plan:NativePlan|null=null,settled=false,fail=false;const conversations=new Map<string,AssistantSnapshot>(),history:ActHistory[]=[];
 const methods=['action.plan','action.confirm','action.reveal','action.undo','actions.list','assistant.send','assistant.state'];
 const conversation=(layerId:string)=>conversations.get(layerId)??{layerId,messages:[],isSending:false,error:null,suggestions:[]};
 const result=(kind:ActResult['kind'],layerId:string|null,planId:string|null,message:string,counts:Record<string,number>,undoable=false):ActResult=>({kind,layerId,planId,actionId:`mock-action:${++sequence}`,ok:true,at:new Date().toISOString(),message,counts,undoable});
 function terminal(value:ActResult){if(value.undoable)history.unshift({actionId:value.actionId,label:value.kind==='open'?'Opened missing entries':'Gathered windows',at:value.at,counts:value.counts,undoable:true});history.splice(10);emit('action.result',value);return value;}
 return {methods,get settled(){return settled;},failNext(){fail=true;},async handle(message:HostEnvelope):Promise<object>{const input=message.payload as {kind:'gather'|'open';layerId:string;entryIndex?:number;planId:string;actionId:string;text:string};
 switch(message.kind){
 case 'action.plan':{const p=fixture().projection,g=p.groups.find(g=>g.id===input.layerId);if(!g)throw Error('Choose a layer.');const ordered=p.entries.filter(e=>e.layerId===g.id).flatMap(e=>e.ranges.map(r=>({e,from:r.from}))).sort((a,b)=>a.from-b.from);const missing=ordered.flatMap(({e},entryIndex)=>{if(g.rows.some(r=>r.entryKeys.includes(e.key))||e.ambiguous||input.entryIndex!==undefined&&input.entryIndex!==entryIndex)return [];const raw=JSON.parse(e.canonical);return [{entryIndex,entryKey:e.key,app:raw.app??null,method:'app' as const,value:raw.app??'Notes',description:`No launch command: opens ${raw.app??'Notes'}, not a ${JSON.stringify(raw.title??'project')} window`}];});
 plan={planId:`mock-plan:${++sequence}`,kind:input.kind,layerId:g.id,layerName:g.label,expiresAt:new Date(Date.now()+60000).toISOString(),layoutCount:input.kind==='open'?0:g.rows.length,putAwayCount:input.kind==='open'?0:null,displaysLeftAlone:(p.displays??[]).filter(d=>!d.main).map(({id,name})=>({id,name})),entries:input.kind==='open'?missing:[],explanation:input.kind==='open'?'Opens only the listed missing entries. Other windows stay where they are.':`Switches to the ${g.label} layer as ⌘⌥1 does, laying out its windows on the main display.`,shortcut:'⌘⌥1',warnings:[]};return plan;}
 case 'action.confirm':{const current=plan;plan=null;if(!current||current.planId!==input.planId)throw Error('Review a fresh plan.');if(fail){fail=false;return terminal({...result(current.kind,current.layerId,current.planId,'Could not complete the action. No other action was attempted.',{}),ok:false});}settled=current.kind==='gather';return terminal(result(current.kind,current.layerId,current.planId,current.kind==='gather'?'Gathered 3 windows and put 6 away':'Requested opening Notes. Opened apps stay open.',current.kind==='gather'?{laidOut:3,putAway:6}:{},true));}
 case 'action.reveal':settled=false;return terminal(result('reveal',null,null,'Showed all windows.',{}));
 case 'action.undo':{const newest=history.find(a=>a.undoable);if(!newest||newest.actionId!==input.actionId)throw Error('Undo the newest action first.');newest.undoable=false;settled=false;return terminal({...result('undo',null,null,`Undid ${newest.label.startsWith('Opened')?'open':'gather'} · restored 9, skipped 1 (you moved Ghostty since).${newest.label.startsWith('Opened')?' Opened apps stay open.':''}`,{restored:9,skipped:1}),undoOfActionId:newest.actionId,reasons:['You moved Ghostty since.']});}
 case 'actions.list':return {actions:history.map(a=>({...a})),newestUndoableActionId:history.find(a=>a.undoable)?.actionId??null};
 case 'assistant.state':return conversation(input.layerId);
 case 'assistant.send':{const previous=conversation(input.layerId),next:AssistantSnapshot={...previous,messages:[...previous.messages,{id:`mock-user:${++sequence}`,role:'user',text:input.text}],isSending:true,suggestions:[]};conversations.set(input.layerId,next);emit('assistant.state',next);setTimeout(()=>{const answer:AssistantSnapshot={...next,isSending:false,messages:[...next.messages,{id:`mock-assistant:${++sequence}`,role:'assistant',text:'Notes has no matching window open. The rule asks for a title containing “Layout notes”. Opening Notes starts the app; Gather will arrange the windows only after you confirm.',readRules:4,readWindows:5}],suggestions:[{label:'Open Notes',kind:'open',layerId:input.layerId,entryIndex:3},{label:'Gather windows',kind:'gather',layerId:input.layerId}]};conversations.set(input.layerId,answer);emit('assistant.state',answer);},80);return {};}
 default:throw Error('Unsupported mock method');
 }}};
}
