// Curated Hudson Design contract for CLI output and agent briefs.
//
// Keep this intentionally small. H Kit should give agents a stable design
// vocabulary before they inspect implementation files, not become a rigid theme
// compiler.

export const ROOT_TOKENS = [
  {
    id: 'surface.bg',
    group: 'surface',
    label: 'Canvas/background surface',
    web: ['--hud-bg'],
    apple: ['HudTheme.palette.bg', 'HudPalette.bg'],
    guidance: 'Use for the deepest app or canvas background.',
  },
  {
    id: 'surface.panel',
    group: 'surface',
    label: 'Raised panel surface',
    web: ['--hud-surface'],
    apple: ['HudTheme.palette.surface', 'HudPalette.surface'],
    guidance: 'Use for panes, cards, drawers, and elevated shell surfaces.',
  },
  {
    id: 'surface.chrome',
    group: 'surface',
    label: 'Shell chrome surface',
    web: ['SHELL_THEME.tokens.bg', '--hud-bg-2'],
    apple: ['HudTheme.palette.chrome', 'HudPalette.chrome'],
    guidance: 'Use for persistent navigation, rails, title bars, and inspectors.',
  },
  {
    id: 'text.ink',
    group: 'text',
    label: 'Primary text',
    web: ['--hud-ink'],
    apple: ['HudTheme.palette.ink', 'HudPalette.ink'],
    guidance: 'Use for primary labels, active row text, and readable body copy.',
  },
  {
    id: 'text.muted',
    group: 'text',
    label: 'Secondary text',
    web: ['--hud-muted'],
    apple: ['HudTheme.palette.muted', 'HudPalette.muted'],
    guidance: 'Use for supporting labels, inactive navigation, and metadata.',
  },
  {
    id: 'text.dim',
    group: 'text',
    label: 'Tertiary text',
    web: ['--hud-dim'],
    apple: ['HudTheme.palette.dim', 'HudPalette.dim'],
    guidance: 'Use for hints, timestamps, disabled text, and soft annotations.',
  },
  {
    id: 'border.subtle',
    group: 'structure',
    label: 'Subtle hairline',
    web: ['--hud-chrome-border-subtle', '--hud-border'],
    apple: ['HudTheme.hairline.subtle', 'HudHairline.subtle'],
    guidance: 'Use for quiet dividers and separators inside dense surfaces.',
  },
  {
    id: 'border.standard',
    group: 'structure',
    label: 'Standard hairline',
    web: ['--hud-border', '--hud-chrome-border'],
    apple: ['HudTheme.hairline.standard', 'HudHairline.standard'],
    guidance: 'Use for panel edges, selected rows, and emphasized dividers.',
  },
  {
    id: 'accent.primary',
    group: 'accent',
    label: 'Primary accent',
    web: ['--hud-accent'],
    apple: ['HudTheme.palette.accent', 'HudPalette.accent'],
    guidance: 'Use for primary selection, focus, active controls, and brand tint.',
  },
  {
    id: 'accent.soft',
    group: 'accent',
    label: 'Soft accent fill',
    web: ['--hud-accent-soft'],
    apple: ['HudTheme.palette.accentSoft', 'HudPalette.accentSoft'],
    guidance: 'Use for selected row fills and non-dominant accent backgrounds.',
  },
  {
    id: 'status.ok',
    group: 'status',
    label: 'Positive/live status',
    web: ['--hud-status-ok'],
    apple: ['HudTheme.palette.statusOk', 'HudPalette.statusOk'],
    guidance: 'Use for ready, live, connected, synced, and healthy states.',
  },
  {
    id: 'status.warn',
    group: 'status',
    label: 'Warning status',
    web: ['--hud-status-warn'],
    apple: ['HudTheme.palette.statusWarn', 'HudPalette.statusWarn'],
    guidance: 'Use for degraded, pending, stale, or attention-needed states.',
  },
  {
    id: 'status.error',
    group: 'status',
    label: 'Error status',
    web: ['--hud-status-error'],
    apple: ['HudTheme.palette.statusError', 'HudPalette.statusError'],
    guidance: 'Use for failed, blocked, destructive, or disconnected states.',
  },
  {
    id: 'status.info',
    group: 'status',
    label: 'Informational status',
    web: ['--hud-status-info'],
    apple: ['HudTheme.palette.statusInfo', 'HudPalette.statusInfo'],
    guidance: 'Use for focus rings, active tools, neutral progress, and inspection.',
  },
  {
    id: 'radius.tight',
    group: 'shape',
    label: 'Tight radius',
    web: ['--hud-radius'],
    apple: ['HudTheme.radius.tight', 'HudRadius.tight'],
    guidance: 'Use for badges, tiny controls, and dense mono chips.',
  },
  {
    id: 'radius.standard',
    group: 'shape',
    label: 'Standard radius',
    web: ['--hud-radius'],
    apple: ['HudTheme.radius.standard', 'HudRadius.standard'],
    guidance: 'Use for controls, input rows, and compact shell elements.',
  },
  {
    id: 'radius.card',
    group: 'shape',
    label: 'Card radius',
    web: ['--hud-radius'],
    apple: ['HudTheme.radius.card', 'HudRadius.card'],
    guidance: 'Use for framed repeated items, cards, and modal surfaces.',
  },
  {
    id: 'layout.navHeight',
    group: 'layout',
    label: 'Primary shell bar height',
    web: ['SHELL_THEME.layout.navHeight'],
    apple: ['HudLayout.navHeight'],
    guidance: 'Use for persistent top bars and native shell headers.',
  },
  {
    id: 'layout.panelWidth',
    group: 'layout',
    label: 'Standard side panel width',
    web: ['SHELL_THEME.layout.panelWidth'],
    apple: ['HudLayout.panelWidth'],
    guidance: 'Use for default sidebars, inspectors, and companion panels.',
  },
  {
    id: 'layout.row.compact',
    group: 'layout',
    label: 'Compact row height',
    web: ['Hudson row pattern'],
    apple: ['HudLayout.rowHeightCompact'],
    guidance: 'Use for dense operational rows and tiny settings surfaces.',
  },
  {
    id: 'layout.row.regular',
    group: 'layout',
    label: 'Regular row height',
    web: ['Hudson row pattern'],
    apple: ['HudLayout.rowHeightRegular'],
    guidance: 'Use for readable settings rows, inspectors, and list items.',
  },
  {
    id: 'type.mono',
    group: 'type',
    label: 'Monospace UI face',
    web: ['--hud-font-mono'],
    apple: ['HudFont.mono'],
    guidance: 'Use for code, counters, token values, status chips, and metadata.',
  },
  {
    id: 'type.ui',
    group: 'type',
    label: 'System UI face',
    web: ['--hud-font-sans'],
    apple: ['HudFont.ui'],
    guidance: 'Use for normal app labels, prose, controls, and titles.',
  },
];

export const DESIGN_PATTERNS = {
  'inspector-settings': {
    title: 'Inspector Settings',
    summary: 'Dense operational settings for shell-like apps where users scan categories, runtime state, and setup switches without leaving the app surface.',
    useWhen: [
      'The settings surface is part of the working shell, not a separate calm account page.',
      'The user needs many compact rows, live values, and configuration checks.',
      'The app has platform capabilities such as voice, terminal, web views, onboarding, or canvas behavior.',
    ],
    tokens: [
      'surface.chrome',
      'surface.panel',
      'text.ink',
      'text.muted',
      'text.dim',
      'border.subtle',
      'border.standard',
      'accent.primary',
      'accent.soft',
      'layout.navHeight',
      'layout.row.regular',
      'type.mono',
    ],
    rules: [
      'Prefer flat sections with hairline separators over nested cards.',
      'Use a compact category rail or tab strip when there are more than four settings groups.',
      'Rows should have a stable height and a predictable trailing value, action, toggle, or segmented choice.',
      'Hints belong inline under or beside labels. Do not turn every row into explanatory prose.',
      'Keep the title owned by the inspector when it is the screen identity; avoid duplicate navigation titles.',
    ],
    antiPatterns: [
      'Marketing copy, feature tours, or oversized hero blocks inside settings.',
      'Cards inside cards.',
      'Purple-heavy accents or decorative gradients.',
      'Controls whose text or labels resize the whole row.',
    ],
    acceptance: [
      'Can an agent identify every color, radius, and row height through root token names?',
      'Does the same category vocabulary translate to web and Apple implementations?',
      'Can the user scan live status and act on rows without reading instructions?',
      'Do rows stay stable under long labels and dynamic values?',
    ],
  },
  'canvas-shell': {
    title: 'Canvas Shell',
    summary: 'A working surface for draggable nodes, tools, side panels, and live status. It should feel like an instrument panel, not a landing page.',
    useWhen: [
      'The app centers on spatial work, terminal nodes, code nodes, workflow graphs, or visual objects.',
      'The user needs chrome, panels, command access, and a persistent status layer.',
    ],
    tokens: [
      'surface.bg',
      'surface.chrome',
      'text.ink',
      'text.muted',
      'border.subtle',
      'accent.primary',
      'status.info',
      'layout.navHeight',
      'layout.panelWidth',
      'type.mono',
    ],
    rules: [
      'Keep the canvas first. Chrome should frame the work, not compete with it.',
      'Panels may be dense, but the world surface should breathe.',
      'Use status color for state, not decoration.',
      'Keep persistent controls dimensionally stable across zoom, hover, and selection.',
    ],
    antiPatterns: [
      'Hero sections, decorative cards, or marketing copy as the first screen.',
      'One-note color palettes that flatten the workspace.',
      'Canvas tools that shift layout when hovered or selected.',
    ],
    acceptance: [
      'Are nodes, panels, and toolbars visually separated through tokenized surfaces?',
      'Can the user tell what is selected, live, stale, and actionable?',
      'Does the shell survive wide, compact, and mobile-ish viewports without overlap?',
    ],
  },
  'terminal-node': {
    title: 'Terminal Node',
    summary: 'A terminal surface that belongs inside Hudson: session-aware, readable, compact, and visually tied to the canvas or shell around it.',
    useWhen: [
      'Rendering local, tmux, ssh, or agent-backed terminal sessions.',
      'Embedding terminal state in a card, node, drawer, or fullscreen surface.',
    ],
    tokens: [
      'surface.bg',
      'surface.panel',
      'text.ink',
      'text.muted',
      'border.standard',
      'status.ok',
      'status.warn',
      'status.error',
      'type.mono',
    ],
    rules: [
      'Use monospace everywhere inside terminal content and terminal metadata.',
      'Distinguish session state with small status indicators, not loud banners.',
      'Preserve text contrast and avoid translucent layers that blur glyph rendering.',
      'Expose reconnect, preserve, and close behavior in shell chrome when relevant.',
    ],
    antiPatterns: [
      'Terminal text inside decorative cards with low contrast.',
      'Hover effects that resize terminal bounds.',
      'Unlabeled disconnected or stale session states.',
    ],
    acceptance: [
      'Can the user read the terminal at node size and fullscreen size?',
      'Is session state obvious without stealing focus?',
      'Does terminal lifecycle behavior match the shell lifecycle?',
    ],
  },
  'onboarding-flow': {
    title: 'Onboarding Flow',
    summary: 'A setup and readiness layer that helps users configure capabilities without turning the app into a wizard-only experience.',
    useWhen: [
      'The app needs permissions, account setup, model/provider setup, terminal setup, or workspace bootstrap.',
      'The user can still benefit from the shell before every item is complete.',
    ],
    tokens: [
      'surface.panel',
      'text.ink',
      'text.muted',
      'text.dim',
      'border.subtle',
      'accent.primary',
      'status.ok',
      'status.warn',
      'status.error',
      'layout.row.regular',
    ],
    rules: [
      'Treat onboarding as readiness state that can live in settings, sheets, or a first-run panel.',
      'Represent each requirement as a row with state, action, and optional detail.',
      'Let users continue when a capability is optional or deferrable.',
      'Keep copy concrete: what is missing, why it matters, what action fixes it.',
    ],
    antiPatterns: [
      'Blocking the whole app for optional capabilities.',
      'Long paragraphs explaining platform permissions.',
      'Unclear setup state such as only showing a spinner or generic error.',
    ],
    acceptance: [
      'Can the user tell which capabilities are ready, optional, missing, or blocked?',
      'Can a later settings surface reopen the same setup affordances?',
      'Does the flow reuse Hudson row, status, and action patterns?',
    ],
  },
};

export const AGENT_INTRO = {
  title: 'Hudson Design Agent Intro',
  summary: 'Hudson Design is the shared product language across web, macOS, and iOS. Web and Apple can keep specialized theme systems, but agents should start from the same root tokens, patterns, and acceptance checks.',
  principles: [
    'Start from a pattern brief before reading implementation files.',
    'Use root token names in reasoning and code review notes.',
    'Translate root tokens through the local platform adapter instead of copying literal colors.',
    'Prefer compact operational UI for shells, tools, terminals, canvases, and inspectors.',
    'Preserve platform-native behavior where it matters: SwiftUI environment on Apple, CSS custom properties on web.',
  ],
  workflow: [
    'Run hkit design intro to load the overall design contract.',
    'Run hkit design brief <pattern> --target <web|ios|macos|apple> before building.',
    'Run hkit design tokens to see token vocabulary and platform mappings.',
    'Run hkit design check to catch unmapped root tokens and unresolved pattern references.',
  ],
};
